###################################################################################################

kind: DaemonSet
apiVersion: "{{ .Values.apiVersionDaemonSet }}"
metadata:
  name: "{{ template "administratorName" . }}"
  namespace: "{{ template "administratorNamespace" . }}"
  labels:
    name: "{{ template "administratorName" . }}"
    chart: "{{ template "administratorChart" . }}"
    release: "{{ template "administratorRelease" . }}"
    heritage: "{{ template "administratorHeritage" . }}"
spec:
  selector:
    matchLabels:
      name: "{{ template "administratorName" . }}"
  template:
    metadata:
      labels:
        name: "{{ template "administratorName" . }}"
        chart: "{{ template "administratorChart" . }}"
        release: "{{ template "administratorRelease" . }}"
        heritage: "{{ template "administratorHeritage" . }}"
    spec:
      hostPID: {{ .Values.hostPID }}
      hostNetwork: {{ .Values.hostNetwork }}
      securityContext:
        fsGroup: {{ .Values.fsGroup }}
        runAsUser: {{ .Values.runAsUser }}
      volumes:
        - name: "{{ .Chart.Name }}"
          hostPath:
            path: /
      containers:
        - name: "{{ .Chart.Name }}"
          image: "{{ template "administratorImage" . }}"
          imagePullPolicy: "{{ .Values.imagePullPolicy }}"
          securityContext:
            privileged: {{ .Values.privileged }}
            readOnlyRootFilesystem: {{ .Values.readOnlyRootFilesystem }}
          command:
{{ toYaml .Values.command | indent 12 }}
          restartPolicy: "{{ .Values.restartPolicy }}"
          volumeMounts:
            - name: "{{ .Chart.Name }}"
              mountPath: "{{ .Values.hostMountPath }}"
          {{- if or .Values.cpu .Values.cpuMinimum .Values.cpuMaximum .Values.memory .Values.memoryMinimum .Values.memoryMaximum }}
          resources:
            {{- if or .Values.cpu .Values.cpuMinimum .Values.memory .Values.memoryMinimum }}
            requests:
              {{- if or .Values.cpu .Values.cpuMinimum }}
              cpu: "{{ if .Values.cpu }}{{ .Values.cpu }}{{ else }}{{ .Values.cpuMinimum }}{{ end }}"
              {{- end }}
              {{- if or .Values.memory .Values.memoryMinimum }}
              memory: "{{ if .Values.memory }}{{ .Values.memory }}{{ else }}{{ .Values.memoryMinimum }}{{ end }}"
              {{- end }}
            {{- end }}
            {{- if or .Values.cpu .Values.cpuMaximum .Values.memory .Values.memoryMaximum }}
            limits:
              {{- if or .Values.cpu .Values.cpuMaximum }}
              cpu: "{{ if .Values.cpu }}{{ .Values.cpu }}{{ else }}{{ .Values.cpuMaximum }}{{ end }}"
              {{- end }}
              {{- if or .Values.memory .Values.memoryMaximum }}
              memory: "{{ if .Values.memory }}{{ .Values.memory }}{{ else }}{{ .Values.memoryMaximum }}{{ end }}"
              {{- end }}
            {{- end }}
          {{- end }}

###################################################################################################
