###################################################################################################

aws:
  region: eu-west-1
  zoneType: private
  accessKey: AKIAJZCLLK633CDE2NMQ
  secretKey:

rbac:
  create: true

policy: sync

logLevel: debug

provider: aws

domainFilters:
  - test.fkaj.com

###################################################################################################
