apiVersion: certmanager.k8s.io/v1alpha1
kind: Certificate
metadata:
  name: vault-digitaltest
  namespace: default
spec:
  secretName: vault-digitaltest
  dnsNames:
    - vault.digitaltest-e.aws.travisperkins.cloud
  acme:
    config:
      - dns01:
          provider: route53
        domains:
          - vault.digitaltest-e.aws.travisperkins.cloud
  issuerRef:
    name: letsencrypt
    kind: ClusterIssuer
