apiVersion: certmanager.k8s.io/v1alpha1
kind: ClusterIssuer
metadata:
  name: letsencrypt
  namespace: default
spec:
  acme:
    server: https://acme-v02.api.letsencrypt.org/directory
    email: ccoe@travisperkins.co.uk
    privateKeySecretRef:
      name: letsencrypt
    dns01:
      providers:
        - name: route53
          route53:
            region: eu-west-1
            accessKeyID: "AKIAJNBRJXDOUL4QPGYQ"
            secretAccessKeySecretRef:
              name: aws-digitaltest
              key: secretAccessKey
