{
 "title": "Nodes",
 "description": "Kubernetes Nodes",
 "tags": [ "Kubernetes" ],
 "time": { "from": "now-3h", "to": "now" },
 "refresh": "5s",
 "panels": [
  {
   "title": "Ready",
   "type": "singlestat",
   "gridPos": { "h": 4, "w": 3, "x": 0, "y": 0 },
   "format": "short",
   "valueName": "current",
   "targets": [
    {
     "expr": "sum(kube_node_status_condition{job=\"kube-state-metrics\",condition=\"Ready\",status=\"true\"})"
    }
   ]
  },
  {
   "title": "Not Ready",
   "type": "singlestat",
   "gridPos": { "h": 4, "w": 3, "x": 3, "y": 0 },
   "format": "short",
   "valueName": "current",
   "targets": [
    {
     "expr": " sum(kube_node_status_condition{job=\"kube-state-metrics\",condition=\"Ready\",status=\"false\"})"
    }
   ]
  },
  {
   "title": "Kernel Deadlock",
   "type": "singlestat",
   "gridPos": { "h": 4, "w": 2, "x": 6, "y": 0 },
   "format": "short",
   "valueName": "current",
   "targets": [
    {
     "expr": " sum(kube_node_status_condition{job=\"kube-state-metrics\",condition=\"KernelDeadlock\",status=\"true\"})"
    }
   ]
  },
  {
   "title": "PID Pressure",
   "type": "singlestat",
   "gridPos": { "h": 4, "w": 2, "x": 8, "y": 0 },
   "format": "short",
   "valueName": "current",
   "targets": [
    {
     "expr": " sum(kube_node_status_condition{job=\"kube-state-metrics\",condition=\"PIDPressure\",status=\"true\"})"
    }
   ]
  },
  {
   "title": "Memory Pressure",
   "type": "singlestat",
   "gridPos": { "h": 4, "w": 2, "x": 10, "y": 0 },
   "format": "short",
   "valueName": "current",
   "targets": [
    {
     "expr": " sum(kube_node_status_condition{job=\"kube-state-metrics\",condition=\"MemoryPressure\",status=\"true\"})"
    }
   ]
  },
  {
   "title": "Disk Pressure",
   "type": "singlestat",
   "gridPos": { "h": 4, "w": 2, "x": 12, "y": 0 },
   "format": "short",
   "valueName": "current",
   "targets": [
    {
     "expr": " sum(kube_node_status_condition{job=\"kube-state-metrics\",condition=\"DiskPressure\",status=\"true\"})"
    }
   ]
  },
  {
   "title": "Out Of Disk",
   "type": "singlestat",
   "gridPos": { "h": 4, "w": 2, "x": 14, "y": 0 },
   "format": "short",
   "valueName": "current",
   "targets": [
    {
     "expr": " sum(kube_node_status_condition{job=\"kube-state-metrics\",condition=\"OutOfDisk\",status=\"true\"})"
    }
   ]
  },
  {
   "title": "Frequent Unregister Net Device",
   "type": "singlestat",
   "gridPos": { "h": 4, "w": 3, "x": 16, "y": 0 },
   "format": "short",
   "valueName": "current",
   "targets": [
    {
     "expr": " sum(kube_node_status_condition{job=\"kube-state-metrics\",condition=\"FrequentUnregisterNetDevice\",status=\"true\"})"
    }
   ]
  },
  {
   "title": "Network Unavailable",
   "type": "singlestat",
   "gridPos": { "h": 4, "w": 3, "x": 19, "y": 0 },
   "format": "short",
   "valueName": "current",
   "targets": [
    {
     "expr": " sum(kube_node_status_condition{job=\"kube-state-metrics\",condition=\"NetworkUnavailable\",status=\"true\"})"
    }
   ]
  },
  {
   "title": "Unknown States",
   "type": "singlestat",
   "gridPos": { "h": 4, "w": 2, "x": 22, "y": 0 },
   "format": "short",
   "valueName": "current",
   "targets": [
    {
     "expr": " sum(kube_node_status_condition{job=\"kube-state-metrics\",status=\"unknown\"})"
    }
   ]
  },
  {
   "title": "CPU Usage",
   "type": "graph",
   "gridPos": { "h": 8, "w": 4, "x": 0, "y": 4 },
   "yaxes": [
    { "format": "percent" }
   ],
   "targets": [
    {
     "expr": "100 - (avg by (instance) (irate(node_cpu_seconds_total{job=\"node-exporter\",mode=\"idle\"}[1m])) * 100)",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "User",
   "type": "graph",
   "gridPos": { "h": 8, "w": 4, "x": 4, "y": 4 },
   "yaxes": [
    { "format": "s" }
   ],
   "targets": [
    {
     "expr": "irate(node_cpu_seconds_total{job=\"node-exporter\",mode=\"user\"}[1m])",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "Kernel",
   "type": "graph",
   "gridPos": { "h": 8, "w": 4, "x": 8, "y": 4 },
   "yaxes": [
    { "format": "s" }
   ],
   "targets": [
    {
     "expr": "irate(node_cpu_seconds_total{job=\"node-exporter\",mode=\"system\"}[1m])",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "Interrupts",
   "type": "graph",
   "gridPos": { "h": 8, "w": 4, "x": 12, "y": 4 },
   "yaxes": [
    { "format": "s" }
   ],
   "targets": [
    {
     "expr": "sum(irate(node_cpu_seconds_total{job=\"node-exporter\",mode=~\"irq|softirq\"}[1m])) by (instance)",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "I/O Wait",
   "type": "graph",
   "gridPos": { "h": 8, "w": 4, "x": 16, "y": 4 },
   "yaxes": [
    { "format": "s" }
   ],
   "targets": [
    {
     "expr": "irate(node_cpu_seconds_total{job=\"node-exporter\",mode=\"iowait\"}[1m])",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "Steal",
   "type": "graph",
   "gridPos": { "h": 8, "w": 4, "x": 20, "y": 4 },
   "yaxes": [
    { "format": "s" }
   ],
   "targets": [
    {
     "expr": "irate(node_cpu_seconds_total{job=\"node-exporter\",mode=\"steal\"}[1m])",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "Context Switches",
   "type": "graph",
   "gridPos": { "h": 8, "w": 4, "x": 0, "y": 12 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "irate(node_context_switches_total{job=\"node-exporter\"}[1m])",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "Interrupts",
   "type": "graph",
   "gridPos": { "h": 8, "w": 4, "x": 4, "y": 12 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "irate(node_intr_total{job=\"node-exporter\"}[1m])",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "API Server HTTP Response Codes",
   "type": "graph",
   "gridPos": { "h": 9, "w": 6, "x": 9, "y": 12 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(rate(apiserver_request_count{code!~\"0\"}[1m])) by (code)",
     "legendFormat": "{{code}}"
    }
   ]
  },
  {
   "title": "Network Errors",
   "type": "graph",
   "gridPos": { "h": 9, "w": 6, "x": 15, "y": 12 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(irate(node_network_transmit_errs_total{job=\"node-exporter\"}[1m])) by (instance, device)",
     "legendFormat": "{{instance}} - {{device}} - tx"
    },
    {
     "expr": "sum(irate(node_network_receive_errs_total{job=\"node-exporter\"}[1m])) by (instance, device)",
     "legendFormat": "{{instance}} - {{device}} - rx"
    }
   ]
  }
 ]
}