###################################################################################################

configName: config
configFile: filebeat.yml
configPath: /usr/share/filebeat

configDataPath: /var/log
configLogsPath: /var/log

configLoggingLevel: info
configLoggingMetricsPeriod: 60s
configLoggingMetricsEnabled: true

configLocaleProcessorEnabled: true

configCloudMetadataProcessorEnabled: true

configDecodeJsonProcessorField: message
configDecodeJsonProcessorTarget: payload
configDecodeJsonProcessorEnabled: true
configDecodeJsonProcessorMaxDepth: 10
configDecodeJsonProcessorProcessArray: true

###################################################################################################
###################################################################################################

podLabels:

###################################################################################################

fsGroup: 1000
runAsUser: 0

###################################################################################################

cpu:
cpuMinimum: 100m
cpuMaximum: 1

###################################################################################################

hostMountName: var
hostMountPath: /var

###################################################################################################

memory:
memoryMinimum: 250Mi
memoryMaximum: 250Mi

###################################################################################################

podAnnotations:

###################################################################################################

podTolerations:

###################################################################################################

imageTag: 6.2.3
imageName: docker.elastic.co/beats/filebeat
imagePullPolicy: IfNotPresent

###################################################################################################

podVolumes:
podVolumeMounts:

###################################################################################################

apiVersionConfigMap: v1
apiVersionDaemonSet: apps/v1

###################################################################################################

readOnlyRootFilesystem: true
allowPrivilegeEscalation: false

###################################################################################################
