###################################################################################################

kind: ClusterIssuer
apiVersion: certmanager.k8s.io/v1alpha1
metadata:
  name: lets-encrypt
  namespace: cert-manager
spec:
  acme:
    email: ccoe@travisperkins.co.uk
    server: https://acme-v02.api.letsencrypt.org/directory
    privateKeySecretRef:
      name: lets-encrypt
    dns01:
      providers:
        - name: route53
          route53:
            region: eu-west-1

###################################################################################################
