apiVersion: v1
kind: ConfigMap
metadata:
  name: kube-dns
  namespace: kube-system
data:
  stubDomains: |
    { "sandpit.fkaj.com": [ "10.228.2.240", "10.228.4.240" ], "travisperkins.digital": [ "10.228.2.240", "10.228.4.240" ] }
  upstreamNameservers: |
    [ "1.1.1.1", "8.8.8.8" ]
