###################################################################################################

kind: ServiceAccount
apiVersion: v1
metadata:
  name: tiller
  namespace: kube-system
  labels:
    name: tiller

###################################################################################################
