###################################################################################################

ingressShim:
  defaultIssuerKind: ClusterIssuer
  defaultIssuerName: cluster-issuer-lets-encrypt

###################################################################################################

podDnsPolicy: None
podDnsConfig:
  nameservers:
    - 1.1.1.1
    - 8.8.8.8

###################################################################################################
