###################################################################################################

controller:
  kind: DaemonSet
  stats:
    enabled: true
  config:
    hsts: 'false'
    enable-modsecurity: 'true'
  metrics:
    enabled: true
  service:
    enableHttp: false
  resources:
    requests:
      cpu: 50m
      memory: 200Mi
    limits:
      cpu: 250m
      memory: 200Mi
  publishService:
    enabled: true
  externalTrafficPolicy: Local

###################################################################################################

defaultBackend:
  resources:
    requests:
      cpu: 10m
      memory: 20Mi
    limits:
      cpu: 10m
      memory: 20Mi

###################################################################################################

podSecurityPolicy:
  enabled: true

###################################################################################################
