###################################################################################################

kind: ConfigMap
apiVersion: "{{ .Values.apiVersionConfigMap }}"
metadata:
  name: "{{ template "grafanaName" . }}"
  namespace: "{{ template "grafanaNamespace" . }}"
  labels:
    name: "{{ template "grafanaName" . }}"
    chart: "{{ template "grafanaChart" . }}"
    release: "{{ template "grafanaRelease" . }}"
    heritage: "{{ template "grafanaHeritage" . }}"
data:
  {{ .Values.configFile }}: |
    instance_name = ${POD_NAME}

###################################################################################################
