###################################################################################################

kind: ConfigMap
apiVersion: "{{ .Values.apiVersionConfigMap }}"
metadata:
  name: "{{ template "grafanaName" . }}"
  namespace: "{{ template "grafanaNamespace" . }}"
  labels:
    name: "{{ template "grafanaName" . }}"
    chart: "{{ template "grafanaChart" . }}"
    release: "{{ template "grafanaRelease" . }}"
    heritage: "{{ template "grafanaHeritage" . }}"
data:
  {{ .Values.configFile }}: |
    instance_name = ${POD_NAME}

    [log]
    level = {{ .Values.configLogLevel }}

    [server]
    http_port = {{ .Values.podPort }}
    router_logging = {{ .Values.configServerRouterLogging }}

    [metrics]
    enabled = {{ .Values.configMetricsEnabled }}
    interval_seconds = {{ .Values.configMetricsInterval }}

    [alerting]
    enabled = {{ .Values.configAlertingEnabled }}
    execute_alerts = {{ .Values.configAlertingExecuteAlerts }}

    [security]
    admin_user = {{ .Values.configSecurityAdminUser }}
    admin_password = {{ .Values.configSecurityAdminPassword }}

    [analytics]
    reporting_enabled = {{ .Values.configAnalyticsReportingEnabled }}

    [dashboards]
    versions_to_keep = {{ .Values.configDashboardsVersionsToKeep }}

    [log.console]
    format = {{ .Values.configLogConsoleFormat }}

  {{- if .Values.configDatasourcePrometheusUrl }}
  {{ .Values.configDatasourcePrometheusFile }}: |
    datasources:
      - type: prometheus
        name: {{ .Values.configDatasourcePrometheusName  }}
        url: {{ .Values.configDatasourcePrometheusUrl }}
  {{- end }}

###################################################################################################
