###################################################################################################

kind: NetworkPolicy
apiVersion: "{{ .Values.apiVersionNetworkPolicy }}"
metadata:
  name: "{{ template "grafanaName" . }}"
  namespace: "{{ template "grafanaNamespace" . }}"
  labels:
    name: "{{ template "grafanaName" . }}"
    chart: "{{ template "grafanaChart" . }}"
    release: "{{ template "grafanaRelease" . }}"
    heritage: "{{ template "grafanaHeritage" . }}"
spec:
  podSelector:
    matchLabels:
      name: "{{ template "grafanaName" . }}"
  ingress:
    - ports:
        - port: {{ .Values.podPort }}

###################################################################################################
