###################################################################################################

rbac:
  create: 'true'

###################################################################################################

verbose: 'true'

###################################################################################################

updateStrategy: RollingUpdate

###################################################################################################
