###################################################################################################

image: gitlab/gitlab-runner:alpine
imagePullPolicy: Always

###################################################################################################

gitlabUrl: http://10.228.2.254/
concurrent: 10
checkInterval: 3
runnerRegistrationToken: "B6Bp514QecidJZxAVfEp"

###################################################################################################

runners:
  namespace: gitlab

###################################################################################################
