###################################################################################################

replicas: 3

###################################################################################################

logLevel: trace

###################################################################################################

storage:
  dynamodb:
    table: Vault
    region: eu-west-1
    ha_enabled: 'true'

###################################################################################################

externalDnsDomainName: test.fkaj.com

###################################################################################################

ingressClass: nginx
ingressAnnotations:
  external-dns/public: 'true'
ingressAnnotationCertManagerClusterIssuer: cluster-issuer-lets-encrypt
ingressAnnotationCertManagerAcmeDns01Provider: route53

###################################################################################################
