{
 "title": "Kubernetes | Node",
 "tags": [
  "Kubernetes",
  "Node"
 ],
 "time": { "from": "now-24h", "to": "now" },
 "refresh": "3m",
 "templating": {
  "list": [
   { "name": "datasource", "label": "Datasource", "query": "prometheus" },
   { "name": "rate_function", "label": "Rate Function", "query": "rate,irate" },
   { "name": "rate_interval", "label": "Rate Interval", "query": "1m,2m,3m,4m,5m,6m,7m,8m,9m,10m" },
   {
    "name": "node",
    "label": "Node",
    "query": "label_values(kube_node_info{job=\"$kube_job\", service=\"$kube_service\"}, node)"
   },
   {
    "name": "instance",
    "query": "label_values(node_uname_info{job=\"$node_job\", service=\"$node_service\", nodename=\"$node\"}, instance)"
   },
   {
    "name": "os_image",
    "query": "label_values(kube_node_info{job=\"$kube_job\", service=\"$kube_service\", node=\"$node\"}, os_image)"
   },
   {
    "name": "kernel_version",
    "query": "label_values(kube_node_info{job=\"$kube_job\", service=\"$kube_service\", node=\"$node\"}, kernel_version)"
   },
   {
    "name": "kubelet_version",
    "query": "label_values(kube_node_info{job=\"$kube_job\", service=\"$kube_service\", node=\"$node\"}, kubelet_version)"
   },
   {
    "name": "container_runtime_version",
    "query": "label_values(kube_node_info{job=\"$kube_job\", service=\"$kube_service\", node=\"$node\"}, container_runtime_version)"
   },
   { "name": "kube_job", "query": "kube-state-metrics" },
   { "name": "kube_service", "query": "monitoring-kube-state-metrics" },
   { "name": "node_job", "query": "node-exporter" },
   {
    "name": "node_service",
    "query": "monitoring-prometheus-node-exporter"
   },
   { "name": "container_job", "query": "kubelet" },
   { "name": "container_service", "query": "prometheus-kubelet" },
   { "name": "node_network_device_regex", "query": "^(en|et|ib|sl|wl|ww).*$" }
  ]
 },
 "panels": [
  {
   "title": "Node Information",
   "type": "text",
   "gridPos": { "h": 5, "w": 24, "x": 0, "y": 0 },
   "content": "```\n\n   Private IP        : $instance\n   Kernel Version    : $kernel_version\n   Kubelet Version   : $kubelet_version\n   Operating System  : $os_image\n   Container Runtime : $container_runtime_version\n\n```"
  },
  {
   "title": "Ready",
   "type": "snuids-trafficlights-panel",
   "gridPos": { "h": 5, "w": 3, "x": 0, "y": 5 },
   "targets": [
    {
     "expr": "scalar(kube_node_status_condition{job=\"$kube_job\", service=\"$kube_service\", node=\"$node\", condition=\"Ready\", status=\"true\"} * 1) + scalar(kube_node_status_condition{job=\"$kube_job\", service=\"$kube_service\", node=\"$node\", condition=\"Ready\", status=\"unknown\"} * 2) + scalar(kube_node_status_condition{job=\"$kube_job\", service=\"$kube_service\", node=\"$node\", condition=\"Ready\", status=\"false\"} * 3)",
     "legendFormat": "Ready"
    }
   ]
  },
  {
   "title": "Memory Pressure",
   "type": "snuids-trafficlights-panel",
   "gridPos": { "h": 5, "w": 3, "x": 3, "y": 5 },
   "targets": [
    {
     "expr": "scalar(kube_node_status_condition{job=\"$kube_job\", service=\"$kube_service\", node=\"$node\", condition=\"MemoryPressure\", status=\"false\"} * 1) + scalar(kube_node_status_condition{job=\"$kube_job\", service=\"$kube_service\", node=\"$node\", condition=\"MemoryPressure\", status=\"unknown\"} * 2) + scalar(kube_node_status_condition{job=\"$kube_job\", service=\"$kube_service\", node=\"$node\", condition=\"MemoryPressure\", status=\"true\"} * 3)",
     "legendFormat": "Memory Pressure"
    }
   ]
  },
  {
   "title": "Disk Pressure",
   "type": "snuids-trafficlights-panel",
   "gridPos": { "h": 5, "w": 3, "x": 6, "y": 5 },
   "targets": [
    {
     "expr": "scalar(kube_node_status_condition{job=\"$kube_job\", service=\"$kube_service\", node=\"$node\", condition=\"DiskPressure\", status=\"false\"} * 1) + scalar(kube_node_status_condition{job=\"$kube_job\", service=\"$kube_service\", node=\"$node\", condition=\"DiskPressure\", status=\"unknown\"} * 2) + scalar(kube_node_status_condition{job=\"$kube_job\", service=\"$kube_service\", node=\"$node\", condition=\"DiskPressure\", status=\"true\"} * 3)",
     "legendFormat": "Disk Pressure"
    }
   ]
  },
  {
   "title": "Out Of Disk",
   "type": "snuids-trafficlights-panel",
   "gridPos": { "h": 5, "w": 3, "x": 9, "y": 5 },
   "targets": [
    {
     "expr": "scalar(kube_node_status_condition{job=\"$kube_job\", service=\"$kube_service\", node=\"$node\", condition=\"OutOfDisk\", status=\"false\"} * 1) + scalar(kube_node_status_condition{job=\"$kube_job\", service=\"$kube_service\", node=\"$node\", condition=\"OutOfDisk\", status=\"unknown\"} * 2) + scalar(kube_node_status_condition{job=\"$kube_job\", service=\"$kube_service\", node=\"$node\", condition=\"OutOfDisk\", status=\"true\"} * 3)",
     "legendFormat": "Out Of Disk"
    }
   ]
  },
  {
   "title": "PID Pressure",
   "type": "snuids-trafficlights-panel",
   "gridPos": { "h": 5, "w": 3, "x": 12, "y": 5 },
   "targets": [
    {
     "expr": "scalar(kube_node_status_condition{job=\"$kube_job\", service=\"$kube_service\", node=\"$node\", condition=\"PIDPressure\", status=\"false\"} * 1) + scalar(kube_node_status_condition{job=\"$kube_job\", service=\"$kube_service\", node=\"$node\", condition=\"PIDPressure\", status=\"unknown\"} * 2) + scalar(kube_node_status_condition{job=\"$kube_job\", service=\"$kube_service\", node=\"$node\", condition=\"PIDPressure\", status=\"true\"} * 3)",
     "legendFormat": "PID Pressure"
    }
   ]
  },
  {
   "title": "Kernel Deadlock",
   "type": "snuids-trafficlights-panel",
   "gridPos": { "h": 5, "w": 3, "x": 15, "y": 5 },
   "targets": [
    {
     "expr": "scalar(kube_node_status_condition{job=\"$kube_job\", service=\"$kube_service\", node=\"$node\", condition=\"KernelDeadlock\", status=\"false\"} * 1) + scalar(kube_node_status_condition{job=\"$kube_job\", service=\"$kube_service\", node=\"$node\", condition=\"KernelDeadlock\", status=\"unknown\"} * 2) + scalar(kube_node_status_condition{job=\"$kube_job\", service=\"$kube_service\", node=\"$node\", condition=\"KernelDeadlock\", status=\"true\"} * 3)",
     "legendFormat": "Kernel Deadlock"
    }
   ]
  },
  {
   "title": "Network Unavailable",
   "type": "snuids-trafficlights-panel",
   "gridPos": { "h": 5, "w": 3, "x": 18, "y": 5 },
   "targets": [
    {
     "expr": "scalar(kube_node_status_condition{job=\"$kube_job\", service=\"$kube_service\", node=\"$node\", condition=\"NetworkUnavailable\", status=\"false\"} * 1) + scalar(kube_node_status_condition{job=\"$kube_job\", service=\"$kube_service\", node=\"$node\", condition=\"NetworkUnavailable\", status=\"unknown\"} * 2) + scalar(kube_node_status_condition{job=\"$kube_job\", service=\"$kube_service\", node=\"$node\", condition=\"NetworkUnavailable\", status=\"true\"} * 3)",
     "legendFormat": "Network Unavailable"
    }
   ]
  },
  {
   "title": "Unregister Net Device",
   "type": "snuids-trafficlights-panel",
   "gridPos": { "h": 5, "w": 3, "x": 21, "y": 5 },
   "targets": [
    {
     "expr": "scalar(kube_node_status_condition{job=\"$kube_job\", service=\"$kube_service\", node=\"$node\", condition=\"FrequentUnregisterNetDevice\", status=\"false\"} * 1) + scalar(kube_node_status_condition{job=\"$kube_job\", service=\"$kube_service\", node=\"$node\", condition=\"FrequentUnregisterNetDevice\", status=\"unknown\"} * 2) + scalar(kube_node_status_condition{job=\"$kube_job\", service=\"$kube_service\", node=\"$node\", condition=\"FrequentUnregisterNetDevice\", status=\"true\"} * 3)",
     "legendFormat": "Unregister Net Device"
    }
   ]
  },
  {
   "title": "CPU Usage",
   "type": "graph",
   "gridPos": { "h": 6, "w": 6, "x": 0, "y": 10 },
   "yaxes": [
    { "format": "percent" }
   ],
   "targets": [
    {
     "expr": "(sum($rate_function(node_cpu_seconds_total{job=\"$node_job\", service=\"$node_service\", instance=~\"^$instance:[0-9]{1,5}\", mode!=\"idle\", mode!=\"iowait\", mode!~\"^(?:guest.*)$\"}[$rate_interval]))) * 100",
     "legendFormat": "CPU Usage"
    }
   ]
  },
  {
   "title": "Memory Usage",
   "type": "graph",
   "gridPos": { "h": 6, "w": 6, "x": 6, "y": 10 },
   "yaxes": [
    { "format": "percent" }
   ],
   "targets": [
    {
     "expr": "(1 - (node_memory_MemAvailable_bytes{job=\"$node_job\", service=\"$node_service\", instance=~\"^$instance:[0-9]{1,5}\"} / node_memory_MemTotal_bytes{job=\"$node_job\", service=\"$node_service\", instance=~\"^$instance:[0-9]{1,5}\"})) * 100",
     "legendFormat": "Memory Usage"
    }
   ]
  },
  {
   "title": "Storage Usage (Device)",
   "type": "graph",
   "gridPos": { "h": 6, "w": 6, "x": 12, "y": 10 },
   "yaxes": [
    { "format": "percent" }
   ],
   "targets": [
    {
     "expr": "(1 - (min(node_filesystem_avail_bytes{job=\"$node_job\", service=\"$node_service\", instance=~\"^$instance:[0-9]{1,5}\", device=~\"^/dev/.*\"}) by (device) / min(node_filesystem_size_bytes{job=\"$node_job\", service=\"$node_service\", instance=~\"^$instance:[0-9]{1,5}\", device=~\"^/dev/.*\"}) by (device))) * 100",
     "legendFormat": "{{device}}"
    }
   ]
  },
  {
   "title": "Network Throughput (Device)",
   "type": "graph",
   "gridPos": { "h": 6, "w": 6, "x": 18, "y": 10 },
   "yaxes": [
    { "format": "decbytes" }
   ],
   "targets": [
    {
     "expr": "$rate_function(node_network_receive_bytes_total{job=\"$node_job\", service=\"$node_service\", instance=~\"^$instance:[0-9]{1,5}\", device=~\"$node_network_device_regex\"}[$rate_interval])",
     "legendFormat": "{{device}} (RX)"
    },
    {
     "expr": "$rate_function(node_network_transmit_bytes_total{job=\"$node_job\", service=\"$node_service\", instance=~\"^$instance:[0-9]{1,5}\", device=~\"$node_network_device_regex\"}[$rate_interval]) * -1",
     "legendFormat": "{{device}} (TX)"
    }
   ]
  },
  { "title": "CPU", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 16 } },
  {
   "title": "CPU Usage",
   "type": "singlestat",
   "gridPos": { "h": 6, "w": 4, "x": 0, "y": 17 },
   "format": "percent",
   "valueName": "current",
   "targets": [
    {
     "expr": "(sum($rate_function(node_cpu_seconds_total{job=\"$node_job\", service=\"$node_service\", instance=~\"^$instance:[0-9]{1,5}\", mode!=\"idle\", mode!=\"iowait\", mode!~\"^(?:guest.*)$\"}[$rate_interval]))) * 100",
     "legendFormat": "CPU Usage"
    }
   ]
  },
  {
   "title": "CPU Usage (Core)",
   "type": "graph",
   "gridPos": { "h": 6, "w": 10, "x": 4, "y": 17 },
   "yaxes": [
    { "format": "percent" }
   ],
   "targets": [
    {
     "expr": "(sum($rate_function(node_cpu_seconds_total{instance=~\"^$instance:[0-9]{1,5}\", mode!=\"idle\", mode!=\"iowait\", mode!~\"^(?:guest.*)$\"}[$rate_interval])) by (cpu)) * 100",
     "legendFormat": "Core {{cpu}}"
    }
   ]
  },
  {
   "title": "System Load",
   "type": "graph",
   "gridPos": { "h": 6, "w": 10, "x": 14, "y": 17 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "node_load1{job=\"$node_job\", service=\"$node_service\", instance=~\"^$instance:[0-9]{1,5}\"}",
     "legendFormat": "1 Minute"
    },
    {
     "expr": "node_load5{job=\"$node_job\", service=\"$node_service\", instance=~\"^$instance:[0-9]{1,5}\"}",
     "legendFormat": "5 Minutes"
    },
    {
     "expr": "node_load15{job=\"$node_job\", service=\"$node_service\", instance=~\"^$instance:[0-9]{1,5}\"}",
     "legendFormat": "15 Minutes"
    }
   ]
  },
  {
   "title": "CPU Allocation (Request)",
   "type": "singlestat",
   "gridPos": { "h": 6, "w": 4, "x": 0, "y": 23 },
   "format": "percent",
   "valueName": "current",
   "targets": [
    {
     "expr": "(sum(kube_pod_container_resource_requests_cpu_cores{job=\"$kube_job\", service=\"$kube_service\", node=\"$node\"}) / sum(kube_node_status_allocatable_cpu_cores{job=\"$kube_job\", service=\"$kube_service\", node=\"$node\"})) * 100",
     "legendFormat": "CPU Allocation (Request)"
    }
   ]
  },
  {
   "title": "CPU Usage (User)",
   "type": "graph",
   "gridPos": { "h": 6, "w": 10, "x": 4, "y": 23 },
   "yaxes": [
    { "format": "percent" }
   ],
   "targets": [
    {
     "expr": "(sum($rate_function(node_cpu_seconds_total{instance=~\"^$instance:[0-9]{1,5}\", mode=\"user\"}[$rate_interval])) by (cpu)) * 100",
     "legendFormat": "Core {{cpu}}"
    }
   ]
  },
  {
   "title": "CPU Usage (System)",
   "type": "graph",
   "gridPos": { "h": 6, "w": 10, "x": 14, "y": 23 },
   "yaxes": [
    { "format": "percent" }
   ],
   "targets": [
    {
     "expr": "(sum($rate_function(node_cpu_seconds_total{instance=~\"^$instance:[0-9]{1,5}\", mode=\"system\"}[$rate_interval])) by (cpu)) * 100",
     "legendFormat": "Core {{cpu}}"
    }
   ]
  },
  {
   "title": "CPU Allocation (Limit)",
   "type": "singlestat",
   "gridPos": { "h": 6, "w": 4, "x": 0, "y": 29 },
   "format": "percent",
   "valueName": "current",
   "targets": [
    {
     "expr": "(sum(kube_pod_container_resource_limits_cpu_cores{job=\"$kube_job\", service=\"$kube_service\", node=\"$node\"}) / sum(kube_node_status_allocatable_cpu_cores{job=\"$kube_job\", service=\"$kube_service\", node=\"$node\"})) * 100",
     "legendFormat": "CPU Allocation (Limit)"
    }
   ]
  },
  {
   "title": "CPU Usage (I/O Wait)",
   "type": "graph",
   "gridPos": { "h": 6, "w": 10, "x": 4, "y": 29 },
   "yaxes": [
    { "format": "percent" }
   ],
   "targets": [
    {
     "expr": "(sum($rate_function(node_cpu_seconds_total{instance=~\"^$instance:[0-9]{1,5}\", mode=\"iowait\"}[$rate_interval])) by (cpu)) * 100",
     "legendFormat": "Core {{cpu}}"
    }
   ]
  },
  {
   "title": "CPU Usage (Steal)",
   "type": "graph",
   "gridPos": { "h": 6, "w": 10, "x": 14, "y": 29 },
   "yaxes": [
    { "format": "percent" }
   ],
   "targets": [
    {
     "expr": "(sum($rate_function(node_cpu_seconds_total{instance=~\"^$instance:[0-9]{1,5}\", mode=\"steal\"}[$rate_interval])) by (cpu)) * 100",
     "legendFormat": "Core {{cpu}}"
    }
   ]
  },
  {
   "title": "CPU Usage (Namespace)",
   "type": "graph",
   "gridPos": { "h": 12, "w": 12, "x": 0, "y": 35 },
   "yaxes": [
    { "format": "percent" }
   ],
   "targets": [
    {
     "expr": "(sum($rate_function(container_cpu_usage_seconds_total{job=\"$container_job\", service=\"$container_service\", node=\"$node\", cpu=\"total\", container_name!=\"\"}[$rate_interval])) by (namespace)) * 100",
     "legendFormat": "{{namespace}}"
    }
   ]
  },
  {
   "title": "CPU Usage (Pod)",
   "type": "graph",
   "gridPos": { "h": 12, "w": 12, "x": 12, "y": 35 },
   "yaxes": [
    { "format": "percent" }
   ],
   "targets": [
    {
     "expr": "(sum($rate_function(container_cpu_usage_seconds_total{job=\"$container_job\", service=\"$container_service\", node=\"$node\", cpu=\"total\", container_name!=\"\"}[$rate_interval])) by (pod_name)) * 100",
     "legendFormat": "{{pod_name}}"
    }
   ]
  },
  { "title": "Memory", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 47 } },
  {
   "title": "Memory Usage",
   "type": "singlestat",
   "gridPos": { "h": 6, "w": 4, "x": 0, "y": 48 },
   "format": "percent",
   "valueName": "current",
   "targets": [
    {
     "expr": "(1 - (node_memory_MemAvailable_bytes{job=\"$node_job\", service=\"$node_service\", instance=~\"^$instance:[0-9]{1,5}\"} / node_memory_MemTotal_bytes{job=\"$node_job\", service=\"$node_service\", instance=~\"^$instance:[0-9]{1,5}\"})) * 100",
     "legendFormat": "Memory Usage"
    }
   ]
  },
  {
   "title": "Memory Usage",
   "type": "graph",
   "gridPos": { "h": 6, "w": 10, "x": 4, "y": 48 },
   "yaxes": [
    { "format": "percent" }
   ],
   "targets": [
    {
     "expr": "(1 - (node_memory_MemAvailable_bytes{job=\"$node_job\", service=\"$node_service\", instance=~\"^$instance:[0-9]{1,5}\"} / node_memory_MemTotal_bytes{job=\"$node_job\", service=\"$node_service\", instance=~\"^$instance:[0-9]{1,5}\"})) * 100",
     "legendFormat": "Memory Usage"
    }
   ]
  },
  {
   "title": "Memory Map",
   "type": "graph",
   "gridPos": { "h": 6, "w": 10, "x": 14, "y": 48 },
   "yaxes": [
    { "format": "percent" }
   ],
   "targets": [
    {
     "expr": "(1 - (node_memory_MemAvailable_bytes{job=\"$node_job\", service=\"$node_service\", instance=~\"^$instance:[0-9]{1,5}\"} / node_memory_MemTotal_bytes{job=\"$node_job\", service=\"$node_service\", instance=~\"^$instance:[0-9]{1,5}\"})) * 100",
     "legendFormat": "Used"
    },
    {
     "expr": "(node_memory_Buffers_bytes{job=\"$node_job\", service=\"$node_service\", instance=~\"^$instance:[0-9]{1,5}\"} / node_memory_MemTotal_bytes{job=\"$node_job\", service=\"$node_service\", instance=~\"^$instance:[0-9]{1,5}\"}) * 100",
     "legendFormat": "Buffers"
    },
    {
     "expr": "(node_memory_Cached_bytes{job=\"$node_job\", service=\"$node_service\", instance=~\"^$instance:[0-9]{1,5}\"} / node_memory_MemTotal_bytes{job=\"$node_job\", service=\"$node_service\", instance=~\"^$instance:[0-9]{1,5}\"}) * 100",
     "legendFormat": "Cached"
    }
   ]
  },
  {
   "title": "Memory Allocation (Request)",
   "type": "singlestat",
   "gridPos": { "h": 6, "w": 4, "x": 0, "y": 54 },
   "format": "percent",
   "valueName": "current",
   "targets": [
    {
     "expr": "(sum(kube_pod_container_resource_requests_memory_bytes{job=\"$kube_job\", service=\"$kube_service\", node=\"$node\"}) / sum(kube_node_status_allocatable_memory_bytes{job=\"$kube_job\", service=\"$kube_service\", node=\"$node\"})) * 100",
     "legendFormat": "Memory Allocation (Request)"
    }
   ]
  },
  {
   "title": "Swapping Activity",
   "type": "graph",
   "gridPos": { "h": 6, "w": 10, "x": 4, "y": 54 },
   "yaxes": [
    { "format": "decbytes" }
   ],
   "targets": [
    {
     "expr": "1000 * sum($rate_function(node_vmstat_pswpin{job=\"$node_job\", service=\"$node_service\", instance=~\"^$instance:[0-9]{1,5}\"}[$rate_interval]) + $rate_function(node_vmstat_pswpout{job=\"$node_job\", service=\"$node_service\", instance=~\"^$instance:[0-9]{1,5}\"}[$rate_interval]))",
     "legendFormat": "Swapping Activity"
    }
   ]
  },
  {
   "title": "Dirty Memory",
   "type": "graph",
   "gridPos": { "h": 6, "w": 10, "x": 14, "y": 54 },
   "yaxes": [
    { "format": "decbytes" }
   ],
   "targets": [
    {
     "expr": "node_memory_Dirty_bytes{job=\"$node_job\", service=\"$node_service\", instance=~\"^$instance:[0-9]{1,5}\"}",
     "legendFormat": "Dirty Memory"
    }
   ]
  },
  {
   "title": "Memory Allocation (Limit)",
   "type": "singlestat",
   "gridPos": { "h": 6, "w": 4, "x": 0, "y": 60 },
   "format": "percent",
   "valueName": "current",
   "targets": [
    {
     "expr": "(sum(kube_pod_container_resource_limits_memory_bytes{job=\"$kube_job\", service=\"$kube_service\", node=\"$node\"}) / sum(kube_node_status_allocatable_memory_bytes{job=\"$kube_job\", service=\"$kube_service\", node=\"$node\"})) * 100",
     "legendFormat": "Memory Allocation (Limit)"
    }
   ]
  },
  {
   "title": "Page Faults (Minor)",
   "type": "graph",
   "gridPos": { "h": 6, "w": 5, "x": 4, "y": 60 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "$rate_function(node_vmstat_pgfault{job=\"$node_job\", service=\"$node_service\", instance=~\"^$instance:[0-9]{1,5}\"}[$rate_interval])",
     "legendFormat": "Page Faults (Minor)"
    }
   ]
  },
  {
   "title": "Page Faults (Major)",
   "type": "graph",
   "gridPos": { "h": 6, "w": 5, "x": 9, "y": 60 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "$rate_function(node_vmstat_pgmajfault{job=\"$node_job\", service=\"$node_service\", instance=~\"^$instance:[0-9]{1,5}\"}[$rate_interval])",
     "legendFormat": "Page Faults (Major)"
    }
   ]
  },
  {
   "title": "Paging Activity",
   "type": "graph",
   "gridPos": { "h": 6, "w": 10, "x": 14, "y": 60 },
   "yaxes": [
    { "format": "decbytes" }
   ],
   "targets": [
    {
     "expr": "1000 * sum($rate_function(node_vmstat_pgpgin{job=\"$node_job\", service=\"$node_service\", instance=~\"^$instance:[0-9]{1,5}\"}[$rate_interval]) + $rate_function(node_vmstat_pgpgout{job=\"$node_job\", service=\"$node_service\", instance=~\"^$instance:[0-9]{1,5}\"}[$rate_interval]))",
     "legendFormat": "Paging Activity"
    }
   ]
  },
  {
   "title": "Memory Usage (Namespace)",
   "type": "graph",
   "gridPos": { "h": 12, "w": 12, "x": 0, "y": 66 },
   "yaxes": [
    { "format": "percent" }
   ],
   "targets": [
    {
     "expr": "(sum(container_memory_usage_bytes{job=\"$container_job\", service=\"$container_service\", node=\"$node\", container_name!=\"\"}) by (namespace) / scalar(node_memory_MemTotal_bytes{job=\"$node_job\", service=\"$node_service\", instance=~\"^$instance:[0-9]{1,5}\"})) * 100",
     "legendFormat": "{{namespace}}"
    }
   ]
  },
  {
   "title": "Memory Usage (Pod)",
   "type": "graph",
   "gridPos": { "h": 12, "w": 12, "x": 12, "y": 66 },
   "yaxes": [
    { "format": "percent" }
   ],
   "targets": [
    {
     "expr": "(sum(container_memory_usage_bytes{job=\"$container_job\", service=\"$container_service\", node=\"$node\", container_name!=\"\"}) by (pod_name) / scalar(node_memory_MemTotal_bytes{job=\"$node_job\", service=\"$node_service\", instance=~\"^$instance:[0-9]{1,5}\"})) * 100",
     "legendFormat": "{{pod_name}}"
    }
   ]
  },
  { "title": "Storage", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 78 } },
  {
   "title": "Storage Usage (Device)",
   "type": "graph",
   "gridPos": { "h": 6, "w": 12, "x": 0, "y": 79 },
   "yaxes": [
    { "format": "percent" }
   ],
   "targets": [
    {
     "expr": "(1 - (min(node_filesystem_avail_bytes{job=\"$node_job\", service=\"$node_service\", instance=~\"^$instance:[0-9]{1,5}\", device=~\"^/dev/.*\"}) by (device) / min(node_filesystem_size_bytes{job=\"$node_job\", service=\"$node_service\", instance=~\"^$instance:[0-9]{1,5}\", device=~\"^/dev/.*\"}) by (device))) * 100",
     "legendFormat": "{{device}}"
    }
   ]
  },
  {
   "title": "Weighted I/O Time (Device)",
   "type": "graph",
   "gridPos": { "h": 6, "w": 12, "x": 12, "y": 79 },
   "yaxes": [
    { "format": "s" }
   ],
   "targets": [
    {
     "expr": "$rate_function(node_disk_io_time_weighted{job=\"$node_job\", service=\"$node_service\", instance=~\"^$instance:[0-9]{1,5}\"}[$rate_interval])",
     "legendFormat": "{{device}}"
    }
   ]
  },
  {
   "title": "Read Operations (Device)",
   "type": "graph",
   "gridPos": { "h": 6, "w": 8, "x": 0, "y": 85 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "$rate_function(node_disk_reads_completed_total{job=\"$node_job\", service=\"$node_service\", instance=~\"^$instance:[0-9]{1,5}\"}[$rate_interval])",
     "legendFormat": "{{device}}"
    }
   ]
  },
  {
   "title": "Read Throughput (Device)",
   "type": "graph",
   "gridPos": { "h": 6, "w": 8, "x": 8, "y": 85 },
   "yaxes": [
    { "format": "decbytes" }
   ],
   "targets": [
    {
     "expr": "$rate_function(node_disk_read_bytes_total{job=\"$node_job\", service=\"$node_service\", instance=~\"^$instance:[0-9]{1,5}\"}[$rate_interval])",
     "legendFormat": "{{device}}"
    }
   ]
  },
  {
   "title": "Read Time (Device)",
   "type": "graph",
   "gridPos": { "h": 6, "w": 8, "x": 16, "y": 85 },
   "yaxes": [
    { "format": "s" }
   ],
   "targets": [
    {
     "expr": "$rate_function(node_disk_read_time_seconds_total{job=\"$node_job\", service=\"$node_service\", instance=~\"^$instance:[0-9]{1,5}\"}[$rate_interval])",
     "legendFormat": "{{device}}"
    }
   ]
  },
  {
   "title": "Write Operations (Device)",
   "type": "graph",
   "gridPos": { "h": 6, "w": 8, "x": 0, "y": 91 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "$rate_function(node_disk_writes_completed_total{job=\"$node_job\", service=\"$node_service\", instance=~\"^$instance:[0-9]{1,5}\"}[$rate_interval])",
     "legendFormat": "{{device}}"
    }
   ]
  },
  {
   "title": "Write Throughput (Device)",
   "type": "graph",
   "gridPos": { "h": 6, "w": 8, "x": 8, "y": 91 },
   "yaxes": [
    { "format": "decbytes" }
   ],
   "targets": [
    {
     "expr": "$rate_function(node_disk_written_bytes_total{job=\"$node_job\", service=\"$node_service\", instance=~\"^$instance:[0-9]{1,5}\"}[$rate_interval])",
     "legendFormat": "{{device}}"
    }
   ]
  },
  {
   "title": "Write Time (Device)",
   "type": "graph",
   "gridPos": { "h": 6, "w": 8, "x": 16, "y": 91 },
   "yaxes": [
    { "format": "s" }
   ],
   "targets": [
    {
     "expr": "$rate_function(node_disk_write_time_seconds_total{job=\"$node_job\", service=\"$node_service\", instance=~\"^$instance:[0-9]{1,5}\"}[$rate_interval])",
     "legendFormat": "{{device}}"
    }
   ]
  },
  { "title": "Network (External)", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 97 } },
  {
   "title": "Receive Throughput (Device)",
   "type": "graph",
   "gridPos": { "h": 6, "w": 8, "x": 0, "y": 98 },
   "yaxes": [
    { "format": "decbytes" }
   ],
   "targets": [
    {
     "expr": "$rate_function(node_network_receive_bytes_total{job=\"$node_job\", service=\"$node_service\", instance=~\"^$instance:[0-9]{1,5}\", device=~\"$node_network_device_regex\"}[$rate_interval])",
     "legendFormat": "{{device}}"
    }
   ]
  },
  {
   "title": "Receive Packets Dropped (Device)",
   "type": "graph",
   "gridPos": { "h": 6, "w": 8, "x": 8, "y": 98 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "$rate_function(node_network_receive_drop_total{job=\"$node_job\", service=\"$node_service\", instance=~\"^$instance:[0-9]{1,5}\", device=~\"$node_network_device_regex\"}[$rate_interval])",
     "legendFormat": "{{device}}"
    }
   ]
  },
  {
   "title": "Receive Errors (Device)",
   "type": "graph",
   "gridPos": { "h": 6, "w": 8, "x": 16, "y": 98 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "$rate_function(node_network_receive_errs_total{job=\"$node_job\", service=\"$node_service\", instance=~\"^$instance:[0-9]{1,5}\", device=~\"$node_network_device_regex\"}[$rate_interval])",
     "legendFormat": "{{device}}"
    }
   ]
  },
  {
   "title": "Transmit Throughput (Device)",
   "type": "graph",
   "gridPos": { "h": 6, "w": 8, "x": 0, "y": 104 },
   "yaxes": [
    { "format": "decbytes" }
   ],
   "targets": [
    {
     "expr": "$rate_function(node_network_transmit_bytes_total{job=\"$node_job\", service=\"$node_service\", instance=~\"^$instance:[0-9]{1,5}\", device=~\"$node_network_device_regex\"}[$rate_interval])",
     "legendFormat": "{{device}}"
    }
   ]
  },
  {
   "title": "Transmit Packets Dropped (Device)",
   "type": "graph",
   "gridPos": { "h": 6, "w": 8, "x": 8, "y": 104 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "$rate_function(node_network_transmit_drop_total{job=\"$node_job\", service=\"$node_service\", instance=~\"^$instance:[0-9]{1,5}\", device=~\"$node_network_device_regex\"}[$rate_interval])",
     "legendFormat": "{{device}}"
    }
   ]
  },
  {
   "title": "Transmit Errors (Device)",
   "type": "graph",
   "gridPos": { "h": 6, "w": 8, "x": 16, "y": 104 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "$rate_function(node_network_transmit_errs_total{job=\"$node_job\", service=\"$node_service\", instance=~\"^$instance:[0-9]{1,5}\", device=~\"$node_network_device_regex\"}[$rate_interval])",
     "legendFormat": "{{device}}"
    }
   ]
  },
  { "title": "Network (Internal)", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 110 } },
  {
   "title": "Receive Throughput (Device)",
   "type": "graph",
   "gridPos": { "h": 6, "w": 8, "x": 0, "y": 111 },
   "yaxes": [
    { "format": "decbytes" }
   ],
   "targets": [
    {
     "expr": "$rate_function(node_network_receive_bytes_total{job=\"$node_job\", service=\"$node_service\", instance=~\"^$instance:[0-9]{1,5}\", device!~\"$node_network_device_regex\"}[$rate_interval])",
     "legendFormat": "{{device}}"
    }
   ]
  },
  {
   "title": "Receive Packets Dropped (Device)",
   "type": "graph",
   "gridPos": { "h": 6, "w": 8, "x": 8, "y": 111 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "$rate_function(node_network_receive_drop_total{job=\"$node_job\", service=\"$node_service\", instance=~\"^$instance:[0-9]{1,5}\", device!~\"$node_network_device_regex\"}[$rate_interval])",
     "legendFormat": "{{device}}"
    }
   ]
  },
  {
   "title": "Receive Errors (Device)",
   "type": "graph",
   "gridPos": { "h": 6, "w": 8, "x": 16, "y": 111 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "$rate_function(node_network_receive_errs_total{job=\"$node_job\", service=\"$node_service\", instance=~\"^$instance:[0-9]{1,5}\", device!~\"$node_network_device_regex\"}[$rate_interval])",
     "legendFormat": "{{device}}"
    }
   ]
  },
  {
   "title": "Transmit Throughput (Device)",
   "type": "graph",
   "gridPos": { "h": 6, "w": 8, "x": 0, "y": 117 },
   "yaxes": [
    { "format": "decbytes" }
   ],
   "targets": [
    {
     "expr": "$rate_function(node_network_transmit_bytes_total{job=\"$node_job\", service=\"$node_service\", instance=~\"^$instance:[0-9]{1,5}\", device!~\"$node_network_device_regex\"}[$rate_interval])",
     "legendFormat": "{{device}}"
    }
   ]
  },
  {
   "title": "Transmit Packets Dropped (Device)",
   "type": "graph",
   "gridPos": { "h": 6, "w": 8, "x": 8, "y": 117 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "$rate_function(node_network_transmit_drop_total{job=\"$node_job\", service=\"$node_service\", instance=~\"^$instance:[0-9]{1,5}\", device!~\"$node_network_device_regex\"}[$rate_interval])",
     "legendFormat": "{{device}}"
    }
   ]
  },
  {
   "title": "Transmit Errors (Device)",
   "type": "graph",
   "gridPos": { "h": 6, "w": 8, "x": 16, "y": 117 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "$rate_function(node_network_transmit_errs_total{job=\"$node_job\", service=\"$node_service\", instance=~\"^$instance:[0-9]{1,5}\", device!~\"$node_network_device_regex\"}[$rate_interval])",
     "legendFormat": "{{device}}"
    }
   ]
  }
 ]
}