{
 "title": "Nodes | Node",
 "tags": [
  "Nodes",
  "Node"
 ],
 "time": { "from": "now-1h", "to": "now" },
 "refresh": "5s",
 "templating": {
  "list": [
   { "name": "datasource", "label": "Datasource", "query": "prometheus" },
   { "name": "rate_function", "label": "Rate Function", "query": "rate,irate" },
   { "name": "rate_interval", "label": "Rate Interval", "query": "1m,2m,3m,4m,5m,6m,7m,8m,9m,10m" },
   {
    "name": "node",
    "label": "Node",
    "query": "label_values(kube_node_info{job=\"$kube_job\", service=\"$kube_service\"}, node)"
   },
   {
    "name": "instance",
    "query": "label_values(node_uname_info{job=\"$node_job\", service=\"$node_service\", nodename=\"$node\"}, instance)"
   },
   { "name": "kube_job", "query": "kube-state-metrics" },
   { "name": "kube_service", "query": "monitoring-kube-state-metrics" },
   { "name": "node_job", "query": "node-exporter" },
   {
    "name": "node_service",
    "query": "monitoring-prometheus-node-exporter"
   },
   { "name": "container_job", "query": "kubelet" },
   { "name": "container_service", "query": "prometheus-kubelet" }
  ]
 },
 "panels": [
  { "title": "Overview", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "CPU Usage",
   "type": "singlestat",
   "gridPos": { "h": 6, "w": 4, "x": 0, "y": 1 },
   "format": "percent",
   "valueName": "current",
   "targets": [
    {
     "expr": "(sum($rate_function(node_cpu_seconds_total{job=\"$node_job\", service=\"$node_service\", instance=~\"^$instance:[0-9]{1,5}\", mode!=\"idle\"}[$rate_interval]))) * 100",
     "legendFormat": "CPU Usage"
    }
   ]
  },
  {
   "title": "Memory Usage",
   "type": "singlestat",
   "gridPos": { "h": 6, "w": 4, "x": 4, "y": 1 },
   "format": "percent",
   "valueName": "current",
   "targets": [
    {
     "expr": "(1 - (node_memory_MemAvailable_bytes{job=\"$node_job\", service=\"$node_service\", instance=~\"^$instance:[0-9]{1,5}\"} / node_memory_MemTotal_bytes{job=\"$node_job\", service=\"$node_service\", instance=~\"^$instance:[0-9]{1,5}\"})) * 100",
     "legendFormat": "Memory Usage"
    }
   ]
  },
  { "title": "Condition", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 7 } },
  {
   "title": "Ready",
   "type": "snuids-trafficlights-panel",
   "gridPos": { "h": 5, "w": 3, "x": 0, "y": 8 },
   "targets": [
    {
     "expr": "scalar(kube_node_status_condition{job=\"$kube_job\", service=\"$kube_service\", node=\"$node\", condition=\"Ready\", status=\"true\"} * 1) + scalar(kube_node_status_condition{job=\"$kube_job\", service=\"$kube_service\", node=\"$node\", condition=\"Ready\", status=\"unknown\"} * 2) + scalar(kube_node_status_condition{job=\"$kube_job\", service=\"$kube_service\", node=\"$node\", condition=\"Ready\", status=\"false\"} * 3)",
     "legendFormat": "Ready"
    }
   ]
  },
  {
   "title": "Memory Pressure",
   "type": "snuids-trafficlights-panel",
   "gridPos": { "h": 5, "w": 3, "x": 3, "y": 8 },
   "targets": [
    {
     "expr": "scalar(kube_node_status_condition{job=\"$kube_job\", service=\"$kube_service\", node=\"$node\", condition=\"MemoryPressure\", status=\"false\"} * 1) + scalar(kube_node_status_condition{job=\"$kube_job\", service=\"$kube_service\", node=\"$node\", condition=\"MemoryPressure\", status=\"unknown\"} * 2) + scalar(kube_node_status_condition{job=\"$kube_job\", service=\"$kube_service\", node=\"$node\", condition=\"MemoryPressure\", status=\"true\"} * 3)",
     "legendFormat": "Memory Pressure"
    }
   ]
  },
  {
   "title": "Disk Pressure",
   "type": "snuids-trafficlights-panel",
   "gridPos": { "h": 5, "w": 3, "x": 6, "y": 8 },
   "targets": [
    {
     "expr": "scalar(kube_node_status_condition{job=\"$kube_job\", service=\"$kube_service\", node=\"$node\", condition=\"DiskPressure\", status=\"false\"} * 1) + scalar(kube_node_status_condition{job=\"$kube_job\", service=\"$kube_service\", node=\"$node\", condition=\"DiskPressure\", status=\"unknown\"} * 2) + scalar(kube_node_status_condition{job=\"$kube_job\", service=\"$kube_service\", node=\"$node\", condition=\"DiskPressure\", status=\"true\"} * 3)",
     "legendFormat": "Disk Pressure"
    }
   ]
  },
  {
   "title": "Out Of Disk",
   "type": "snuids-trafficlights-panel",
   "gridPos": { "h": 5, "w": 3, "x": 9, "y": 8 },
   "targets": [
    {
     "expr": "scalar(kube_node_status_condition{job=\"$kube_job\", service=\"$kube_service\", node=\"$node\", condition=\"OutOfDisk\", status=\"false\"} * 1) + scalar(kube_node_status_condition{job=\"$kube_job\", service=\"$kube_service\", node=\"$node\", condition=\"OutOfDisk\", status=\"unknown\"} * 2) + scalar(kube_node_status_condition{job=\"$kube_job\", service=\"$kube_service\", node=\"$node\", condition=\"OutOfDisk\", status=\"true\"} * 3)",
     "legendFormat": "Out Of Disk"
    }
   ]
  },
  {
   "title": "PID Pressure",
   "type": "snuids-trafficlights-panel",
   "gridPos": { "h": 5, "w": 3, "x": 12, "y": 8 },
   "targets": [
    {
     "expr": "scalar(kube_node_status_condition{job=\"$kube_job\", service=\"$kube_service\", node=\"$node\", condition=\"PIDPressure\", status=\"false\"} * 1) + scalar(kube_node_status_condition{job=\"$kube_job\", service=\"$kube_service\", node=\"$node\", condition=\"PIDPressure\", status=\"unknown\"} * 2) + scalar(kube_node_status_condition{job=\"$kube_job\", service=\"$kube_service\", node=\"$node\", condition=\"PIDPressure\", status=\"true\"} * 3)",
     "legendFormat": "PID Pressure"
    }
   ]
  },
  {
   "title": "Kernel Deadlock",
   "type": "snuids-trafficlights-panel",
   "gridPos": { "h": 5, "w": 3, "x": 15, "y": 8 },
   "targets": [
    {
     "expr": "scalar(kube_node_status_condition{job=\"$kube_job\", service=\"$kube_service\", node=\"$node\", condition=\"KernelDeadlock\", status=\"false\"} * 1) + scalar(kube_node_status_condition{job=\"$kube_job\", service=\"$kube_service\", node=\"$node\", condition=\"KernelDeadlock\", status=\"unknown\"} * 2) + scalar(kube_node_status_condition{job=\"$kube_job\", service=\"$kube_service\", node=\"$node\", condition=\"KernelDeadlock\", status=\"true\"} * 3)",
     "legendFormat": "Kernel Deadlock"
    }
   ]
  },
  {
   "title": "Network Unavailable",
   "type": "snuids-trafficlights-panel",
   "gridPos": { "h": 5, "w": 3, "x": 18, "y": 8 },
   "targets": [
    {
     "expr": "scalar(kube_node_status_condition{job=\"$kube_job\", service=\"$kube_service\", node=\"$node\", condition=\"NetworkUnavailable\", status=\"false\"} * 1) + scalar(kube_node_status_condition{job=\"$kube_job\", service=\"$kube_service\", node=\"$node\", condition=\"NetworkUnavailable\", status=\"unknown\"} * 2) + scalar(kube_node_status_condition{job=\"$kube_job\", service=\"$kube_service\", node=\"$node\", condition=\"NetworkUnavailable\", status=\"true\"} * 3)",
     "legendFormat": "Network Unavailable"
    }
   ]
  },
  {
   "title": "Unregister Net Device",
   "type": "snuids-trafficlights-panel",
   "gridPos": { "h": 5, "w": 3, "x": 21, "y": 8 },
   "targets": [
    {
     "expr": "scalar(kube_node_status_condition{job=\"$kube_job\", service=\"$kube_service\", node=\"$node\", condition=\"FrequentUnregisterNetDevice\", status=\"false\"} * 1) + scalar(kube_node_status_condition{job=\"$kube_job\", service=\"$kube_service\", node=\"$node\", condition=\"FrequentUnregisterNetDevice\", status=\"unknown\"} * 2) + scalar(kube_node_status_condition{job=\"$kube_job\", service=\"$kube_service\", node=\"$node\", condition=\"FrequentUnregisterNetDevice\", status=\"true\"} * 3)",
     "legendFormat": "Unregister Net Device"
    }
   ]
  },
  { "title": "CPU", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 13 } },
  {
   "title": "CPU Usage (Core)",
   "type": "graph",
   "gridPos": { "h": 6, "w": 12, "x": 0, "y": 14 },
   "yaxes": [
    { "format": "percent" }
   ],
   "targets": [
    {
     "expr": "(sum($rate_function(node_cpu_seconds_total{instance=~\"^$instance:[0-9]{1,5}\", mode!=\"idle\"}[$rate_interval])) by (cpu)) * 100",
     "legendFormat": "Core {{cpu}}"
    }
   ]
  },
  {
   "title": "System Load",
   "type": "graph",
   "gridPos": { "h": 6, "w": 12, "x": 12, "y": 14 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "node_load1{job=\"$node_job\", service=\"$node_service\", instance=~\"^$instance:[0-9]{1,5}\"}",
     "legendFormat": "1 Minute"
    },
    {
     "expr": "node_load5{job=\"$node_job\", service=\"$node_service\", instance=~\"^$instance:[0-9]{1,5}\"}",
     "legendFormat": "5 Minutes"
    },
    {
     "expr": "node_load15{job=\"$node_job\", service=\"$node_service\", instance=~\"^$instance:[0-9]{1,5}\"}",
     "legendFormat": "15 Minutes"
    }
   ]
  },
  {
   "title": "CPU Usage (User)",
   "type": "graph",
   "gridPos": { "h": 6, "w": 6, "x": 0, "y": 20 },
   "yaxes": [
    { "format": "percent" }
   ],
   "targets": [
    {
     "expr": "(sum($rate_function(node_cpu_seconds_total{instance=~\"^$instance:[0-9]{1,5}\", mode=\"user\"}[$rate_interval])) by (cpu)) * 100",
     "legendFormat": "Core {{cpu}}"
    }
   ]
  },
  {
   "title": "CPU Usage (System)",
   "type": "graph",
   "gridPos": { "h": 6, "w": 6, "x": 6, "y": 20 },
   "yaxes": [
    { "format": "percent" }
   ],
   "targets": [
    {
     "expr": "(sum($rate_function(node_cpu_seconds_total{instance=~\"^$instance:[0-9]{1,5}\", mode=\"system\"}[$rate_interval])) by (cpu)) * 100",
     "legendFormat": "Core {{cpu}}"
    }
   ]
  },
  {
   "title": "CPU Usage (I/O Wait)",
   "type": "graph",
   "gridPos": { "h": 6, "w": 6, "x": 12, "y": 20 },
   "yaxes": [
    { "format": "percent" }
   ],
   "targets": [
    {
     "expr": "(sum($rate_function(node_cpu_seconds_total{instance=~\"^$instance:[0-9]{1,5}\", mode=\"iowait\"}[$rate_interval])) by (cpu)) * 100",
     "legendFormat": "Core {{cpu}}"
    }
   ]
  },
  {
   "title": "CPU Usage (Steal)",
   "type": "graph",
   "gridPos": { "h": 6, "w": 6, "x": 18, "y": 20 },
   "yaxes": [
    { "format": "percent" }
   ],
   "targets": [
    {
     "expr": "(sum($rate_function(node_cpu_seconds_total{instance=~\"^$instance:[0-9]{1,5}\", mode=\"steal\"}[$rate_interval])) by (cpu)) * 100",
     "legendFormat": "Core {{cpu}}"
    }
   ]
  },
  {
   "title": "CPU Allocation (Request)",
   "type": "singlestat",
   "gridPos": { "h": 6, "w": 4, "x": 0, "y": 26 },
   "format": "percent",
   "valueName": "current",
   "targets": [
    {
     "expr": "(sum(kube_pod_container_resource_requests_cpu_cores{job=\"$kube_job\", service=\"$kube_service\", node=\"$node\"}) / sum(kube_node_status_allocatable_cpu_cores{job=\"$kube_job\", service=\"$kube_service\", node=\"$node\"})) * 100",
     "legendFormat": "CPU Allocation (Request)"
    }
   ]
  },
  {
   "title": "CPU Usage (Namespace)",
   "type": "graph",
   "gridPos": { "h": 12, "w": 10, "x": 4, "y": 26 },
   "yaxes": [
    { "format": "percent" }
   ],
   "targets": [
    {
     "expr": "(sum($rate_function(container_cpu_usage_seconds_total{job=\"$container_job\", service=\"$container_service\", node=\"$node\", cpu=\"total\", container_name!=\"\"}[$rate_interval])) by (namespace)) * 100",
     "legendFormat": "{{namespace}}"
    }
   ]
  },
  {
   "title": "CPU Usage (Pod)",
   "type": "graph",
   "gridPos": { "h": 12, "w": 10, "x": 14, "y": 26 },
   "yaxes": [
    { "format": "percent" }
   ],
   "targets": [
    {
     "expr": "(sum($rate_function(container_cpu_usage_seconds_total{job=\"$container_job\", service=\"$container_service\", node=\"$node\", cpu=\"total\", container_name!=\"\"}[$rate_interval])) by (pod_name)) * 100",
     "legendFormat": "{{pod_name}}"
    }
   ]
  },
  {
   "title": "CPU Allocation (Limit)",
   "type": "singlestat",
   "gridPos": { "h": 6, "w": 4, "x": 0, "y": 32 },
   "format": "percent",
   "valueName": "current",
   "targets": [
    {
     "expr": "(sum(kube_pod_container_resource_limits_cpu_cores{job=\"$kube_job\", service=\"$kube_service\", node=\"$node\"}) / sum(kube_node_status_allocatable_cpu_cores{job=\"$kube_job\", service=\"$kube_service\", node=\"$node\"})) * 100",
     "legendFormat": "CPU Allocation (Limit)"
    }
   ]
  },
  { "title": "Memory", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 38 } },
  { "title": "Storage", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 39 } },
  { "title": "Network", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 40 } }
 ]
}