{
 "title": "Level 1",
 "tags": [
  "Vault",
  "Level 1"
 ],
 "time": { "from": "now-5m", "to": "now" },
 "refresh": "5s",
 "templating": {
  "list": [
   { "name": "rate", "query": "${VAR_RATE}" },
   { "name": "irate", "query": "${VAR_IRATE}" },
   { "name": "container", "query": "${VAR_CONTAINER}" },
   { "name": "statefulset", "query": "${VAR_STATEFULSET}" },
   { "name": "namespace", "query": "${VAR_NAMESPACE}" },
   { "name": "kube_job", "query": "${VAR_KUBE_JOB}" },
   { "name": "kube_service", "query": "${VAR_KUBE_SERVICE}" },
   { "name": "container_job", "query": "${VAR_CONTAINER_JOB}" },
   { "name": "container_service", "query": "${VAR_CONTAINER_SERVICE}" }
  ]
 },
 "panels": [
  {
   "title": "Replicas",
   "type": "singlestat",
   "gridPos": { "h": 10, "w": 7, "x": 0, "y": 0 },
   "format": "short",
   "valueName": "current",
   "targets": [
    {
     "expr": "kube_statefulset_replicas{job=\"${kube_job}\", service=\"${kube_service}\", namespace=\"${namespace}\", statefulset=\"${statefulset}\"}"
    }
   ]
  },
  {
   "title": "CPU Usage (Allocation)",
   "type": "singlestat",
   "gridPos": { "h": 10, "w": 6, "x": 7, "y": 0 },
   "format": "percent",
   "valueName": "current",
   "targets": [
    {
     "expr": "((sum(label_replace(irate(container_cpu_usage_seconds_total{job=\"${container_job}\", service=\"${container_service}\", namespace=\"${namespace}\", container_name=\"${container}\"}[${irate}]), \"pod\", \"${1}\", \"pod_name\", \"(.+)\"))) / (sum(kube_pod_container_resource_limits_cpu_cores{job=\"${kube_job}\", service=\"${kube_service}\", namespace=\"${namespace}\", container=\"${container}\"})) * 100)"
    }
   ]
  },
  {
   "title": "Memory Usage (Allocation)",
   "type": "singlestat",
   "gridPos": { "h": 10, "w": 6, "x": 13, "y": 0 },
   "format": "percent",
   "valueName": "current",
   "targets": [
    {
     "expr": "((sum(label_replace(container_memory_usage_bytes{job=\"${container_job}\", service=\"${container_service}\", namespace=\"${namespace}\", container_name=\"${container}\"}, \"pod\", \"${1}\", \"pod_name\", \"(.+)\"))) / sum(kube_pod_container_resource_limits_memory_bytes{job=\"${kube_job}\", service=\"${kube_service}\", namespace=\"${namespace}\", container=\"${container}\"}) * 100)"
    }
   ]
  },
  {
   "title": "Network Receive Rate",
   "type": "singlestat",
   "gridPos": { "h": 2, "w": 5, "x": 19, "y": 0 },
   "format": "bytes",
   "valueName": "current",
   "targets": [
    {
     "expr": "sum(irate(container_network_receive_bytes_total{job=\"${container_job}\", service=\"${container_service}\", namespace=\"${namespace}\"}[$irate]))"
    }
   ]
  },
  {
   "title": "Network Receive Errors",
   "type": "singlestat",
   "gridPos": { "h": 4, "w": 5, "x": 19, "y": 2 },
   "format": "short",
   "valueName": "max",
   "targets": [
    {
     "expr": "sum(rate(container_network_receive_errors_total{job=\"${container_job}\", service=\"${container_service}\", namespace=\"${namespace}\"}[${rate}]))"
    }
   ]
  },
  {
   "title": "Network Receive Packets Dropped",
   "type": "singlestat",
   "gridPos": { "h": 4, "w": 5, "x": 19, "y": 6 },
   "format": "short",
   "valueName": "max",
   "targets": [
    {
     "expr": "sum(rate(container_network_receive_packets_dropped_total{job=\"${container_job}\", service=\"${container_service}\", namespace=\"${namespace}\"}[${rate}]))"
    }
   ]
  },
  {
   "title": "Ready Pods",
   "type": "singlestat",
   "gridPos": { "h": 10, "w": 7, "x": 0, "y": 10 },
   "format": "short",
   "valueName": "current",
   "targets": [
    {
     "expr": "kube_statefulset_status_replicas_ready{job=\"${kube_job}\", service=\"${kube_service}\", namespace=\"${namespace}\", statefulset=\"${statefulset}\"}"
    }
   ]
  },
  {
   "title": "CPU Usage (Distribution)",
   "type": "grafana-piechart-panel",
   "gridPos": { "h": 10, "w": 6, "x": 7, "y": 10 },
   "format": "short",
   "valueName": "current",
   "targets": [
    {
     "expr": "irate(container_cpu_usage_seconds_total{job=\"${container_job}\", service=\"${container_service}\", namespace=\"${namespace}\", container_name=\"${container}\"}[${irate}])",
     "legendFormat": "{{pod_name}}"
    }
   ]
  },
  {
   "title": "Memory Usage (Distribution)",
   "type": "grafana-piechart-panel",
   "gridPos": { "h": 10, "w": 6, "x": 13, "y": 10 },
   "format": "short",
   "valueName": "current",
   "targets": [
    {
     "expr": "container_memory_usage_bytes{job=\"${container_job}\", service=\"${container_service}\", namespace=\"${namespace}\", container_name=\"${container}\"}",
     "legendFormat": "{{pod_name}}"
    }
   ]
  },
  {
   "title": "Network Transmit Rate",
   "type": "singlestat",
   "gridPos": { "h": 2, "w": 5, "x": 19, "y": 10 },
   "format": "bytes",
   "valueName": "current",
   "targets": [
    {
     "expr": "sum(irate(container_network_transmit_bytes_total{job=\"${container_job}\", service=\"${container_service}\", namespace=\"${namespace}\"}[$irate]))"
    }
   ]
  },
  {
   "title": "Network Transmit Errors",
   "type": "singlestat",
   "gridPos": { "h": 4, "w": 5, "x": 19, "y": 12 },
   "format": "short",
   "valueName": "max",
   "targets": [
    {
     "expr": "sum(rate(container_network_transmit_errors_total{job=\"${container_job}\", service=\"${container_service}\", namespace=\"${namespace}\"}[${rate}]))"
    }
   ]
  },
  {
   "title": "Network Transmit Packets Dropped",
   "type": "singlestat",
   "gridPos": { "h": 4, "w": 5, "x": 19, "y": 16 },
   "format": "short",
   "valueName": "max",
   "targets": [
    {
     "expr": "sum(rate(container_network_transmit_packets_dropped_total{job=\"${container_job}\", service=\"${container_service}\", namespace=\"${namespace}\"}[${rate}]))"
    }
   ]
  }
 ]
}