{
 "title": "Vault / Level 2",
 "tags": [
  "Vault",
  "Level 2"
 ],
 "time": { "from": "now-5m", "to": "now" },
 "refresh": "5s",
 "templating": {
  "list": [
   { "name": "rate", "query": "${VAR_RATE}" },
   { "name": "irate", "query": "${VAR_IRATE}" },
   { "name": "container", "query": "${VAR_CONTAINER}" },
   { "name": "statefulset", "query": "${VAR_STATEFULSET}" },
   { "name": "namespace", "query": "${VAR_NAMESPACE}" },
   { "name": "kube_job", "query": "${VAR_KUBE_JOB}" },
   { "name": "kube_service", "query": "${VAR_KUBE_SERVICE}" },
   { "name": "container_job", "query": "${VAR_CONTAINER_JOB}" },
   { "name": "container_service", "query": "${VAR_CONTAINER_SERVICE}" }
  ]
 },
 "panels": [
  {
   "title": "Replicas",
   "type": "singlestat",
   "gridPos": { "h": 8, "w": 4, "x": 0, "y": 0 },
   "format": "short",
   "valueName": "current",
   "targets": [
    {
     "expr": "kube_statefulset_status_replicas{namespace=\"${namespace}\",statefulset=\"${statefulset}\"}"
    }
   ]
  },
  {
   "title": "Running",
   "type": "singlestat",
   "gridPos": { "h": 8, "w": 4, "x": 4, "y": 0 },
   "format": "short",
   "valueName": "current",
   "targets": [
    {
     "expr": "kube_statefulset_status_replicas_current{namespace=\"${namespace}\",statefulset=\"${statefulset}\"}"
    }
   ]
  },
  {
   "title": "Ready",
   "type": "singlestat",
   "gridPos": { "h": 8, "w": 4, "x": 8, "y": 0 },
   "format": "short",
   "valueName": "current",
   "targets": [
    {
     "expr": "kube_statefulset_status_replicas_ready{namespace=\"${namespace}\",statefulset=\"${statefulset}\"}"
    }
   ]
  },
  {
   "title": "Total CPU Usage (Request)",
   "type": "singlestat",
   "gridPos": { "h": 9, "w": 5, "x": 1, "y": 8 },
   "format": "percent",
   "valueName": "current",
   "targets": [
    {
     "expr": "(sum(label_replace(irate(container_cpu_usage_seconds_total{job=\"kubelet\", service=\"kubelet\", namespace=\"vault\", container_name=\"vault\"}[1m]), \"pod\", \"${1}\", \"pod_name\", \"(.+)\"))) / (sum(kube_pod_container_resource_requests_cpu_cores{job=\"kube-state-metrics\", service=\"monitoring-kube-state-metrics\", namespace=\"vault\", container=\"vault\"})) * 100"
    }
   ]
  }
 ]
}