{
 "title": "Vault | USE",
 "description": "The USE Method (Utilisation, Saturation, Errors)",
 "tags": [
  "Vault",
  "USE"
 ],
 "time": { "from": "now-3h", "to": "now" },
 "refresh": "3s",
 "templating": {
  "list": [
   { "name": "rate", "query": "3m" },
   { "name": "irate", "query": "1m" },
   { "name": "container", "query": "vault" },
   { "name": "statefulset", "query": "vault-vault" },
   { "name": "namespace", "query": "vault" },
   { "name": "kube_job", "query": "kube-state-metrics" },
   { "name": "kube_service", "query": "monitoring-kube-state-metrics" },
   { "name": "container_job", "query": "kubelet" },
   { "name": "container_service", "query": "kubelet" },
   {
    "name": "nginx_ingress_job",
    "query": "nginx-ingress-controller-metrics"
   },
   {
    "name": "nginx_ingress_service",
    "query": "nginx-ingress-controller-metrics"
   }
  ]
 },
 "panels": [
  {
   "title": "CPU Utilisation",
   "type": "graph",
   "gridPos": { "h": 6, "w": 8, "x": 0, "y": 0 },
   "yaxes": [
    { "format": "percent" }
   ],
   "targets": [
    {
     "expr": "((sum(label_replace(rate(container_cpu_usage_seconds_total{job=\"${container_job}\", service=\"${container_service}\", namespace=\"${namespace}\", container_name=\"${container}\"}[${rate}]), \"pod\", \"${1}\", \"pod_name\", \"(.+)\")) by (pod)) / (sum(kube_pod_container_resource_requests_cpu_cores{job=\"${kube_job}\", service=\"${kube_service}\", namespace=\"${namespace}\", container=\"${container}\"}) by (pod))) * 100",
     "legendFormat": "{{pod}}"
    }
   ]
  },
  {
   "title": "Aggregate CPU Utilisation",
   "type": "singlestat",
   "gridPos": { "h": 6, "w": 4, "x": 8, "y": 0 },
   "format": "percent",
   "valueName": "current",
   "targets": [
    {
     "expr": "(sum(label_replace(rate(container_cpu_usage_seconds_total{job=\"${container_job}\", service=\"${container_service}\", namespace=\"${namespace}\", container_name=\"${container}\"}[${rate}]), \"pod\", \"${1}\", \"pod_name\", \"(.+)\")) / sum(kube_pod_container_resource_requests_cpu_cores{job=\"${kube_job}\", service=\"${kube_service}\", namespace=\"${namespace}\", container=\"${container}\"})) * 100"
    }
   ]
  },
  {
   "title": "CPU Saturation",
   "type": "graph",
   "gridPos": { "h": 6, "w": 8, "x": 12, "y": 0 },
   "yaxes": [
    { "format": "percent" }
   ],
   "targets": [
    {
     "expr": "sum(rate(container_cpu_cfs_throttled_seconds_total{job=\"${container_job}\", service=\"${container_service}\", namespace=\"${namespace}\", container_name=\"${container}\"}[${rate}])) by (pod_name) * 100",
     "legendFormat": "{{pod_name}}"
    }
   ]
  },
  {
   "title": "Aggregate CPU Saturation",
   "type": "singlestat",
   "gridPos": { "h": 6, "w": 4, "x": 20, "y": 0 },
   "format": "percent",
   "valueName": "current",
   "targets": [
    {
     "expr": "sum(rate(container_cpu_cfs_throttled_seconds_total{job=\"${container_job}\", service=\"${container_service}\", namespace=\"${namespace}\", container_name=\"${container}\"}[${rate}])) * 100"
    }
   ]
  },
  {
   "title": "Memory Utilisation",
   "type": "graph",
   "gridPos": { "h": 6, "w": 8, "x": 0, "y": 6 },
   "yaxes": [
    { "format": "decbytes" }
   ],
   "targets": [
    {
     "expr": "container_memory_working_set_bytes{job=\"${container_job}\", service=\"${container_service}\", namespace=\"${namespace}\", container_name=\"${container}\"}",
     "legendFormat": "{{pod_name}}"
    }
   ]
  },
  {
   "title": "Aggregate Memory Utilisation",
   "type": "singlestat",
   "gridPos": { "h": 6, "w": 4, "x": 8, "y": 6 },
   "format": "decbytes",
   "valueName": "current",
   "targets": [
    {
     "expr": "sum(container_memory_working_set_bytes{job=\"${container_job}\", service=\"${container_service}\", namespace=\"${namespace}\", container_name=\"${container}\"})"
    }
   ]
  },
  {
   "title": "Memory Saturation",
   "type": "graph",
   "gridPos": { "h": 6, "w": 8, "x": 12, "y": 6 },
   "yaxes": [
    { "format": "percent" }
   ],
   "targets": [
    {
     "expr": "(sum(container_memory_working_set_bytes{job=\"${container_job}\", service=\"${container_service}\", namespace=\"${namespace}\", container_name=\"${container}\"}) by (pod_name) / sum(label_replace(kube_pod_container_resource_limits_memory_bytes{job=\"${kube_job}\", service=\"${kube_service}\", namespace=\"${namespace}\", container=\"${container}\"}, \"pod_name\", \"${1}\", \"pod\", \"(.+)\")) by (pod_name)) * 100",
     "legendFormat": "{{pod_name}}"
    }
   ]
  },
  {
   "title": "Aggregate Memory Saturation",
   "type": "singlestat",
   "gridPos": { "h": 6, "w": 4, "x": 20, "y": 6 },
   "format": "percent",
   "valueName": "current",
   "targets": [
    {
     "expr": "(sum(container_memory_working_set_bytes{job=\"${container_job}\", service=\"${container_service}\", namespace=\"${namespace}\", container_name=\"${container}\"}) / sum(label_replace(kube_pod_container_resource_limits_memory_bytes{job=\"${kube_job}\", service=\"${kube_service}\", namespace=\"${namespace}\", container=\"${container}\"}, \"pod_name\", \"${1}\", \"pod\", \"(.+)\"))) * 100"
    }
   ]
  },
  {
   "title": "Network Utilisation",
   "type": "graph",
   "gridPos": { "h": 6, "w": 8, "x": 0, "y": 12 },
   "yaxes": [
    { "format": "decbytes" }
   ],
   "targets": [
    {
     "expr": "rate(container_network_receive_bytes_total{job=\"${container_job}\", service=\"${container_service}\", namespace=\"${namespace}\"}[${rate}]) + rate(container_network_transmit_bytes_total{job=\"${container_job}\", service=\"${container_service}\", namespace=\"${namespace}\"}[${rate}])",
     "legendFormat": "{{pod_name}}"
    }
   ]
  },
  {
   "title": "Aggregate Network Utilisation",
   "type": "singlestat",
   "gridPos": { "h": 6, "w": 4, "x": 8, "y": 12 },
   "format": "decbytes",
   "valueName": "current",
   "targets": [
    {
     "expr": "sum(rate(container_network_receive_bytes_total{job=\"${container_job}\", service=\"${container_service}\", namespace=\"${namespace}\"}[${rate}])) + sum(rate(container_network_transmit_bytes_total{job=\"${container_job}\", service=\"${container_service}\", namespace=\"${namespace}\"}[${rate}]))"
    }
   ]
  },
  {
   "title": "Network Errors",
   "type": "graph",
   "gridPos": { "h": 6, "w": 8, "x": 12, "y": 12 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(rate(container_network_receive_errors_total{job=\"${container_job}\", service=\"${container_service}\", namespace=\"${namespace}\"}[${rate}])) by (pod_name) + sum(rate(container_network_receive_packets_dropped_total{job=\"${container_job}\", service=\"${container_service}\", namespace=\"${namespace}\"}[${rate}])) by (pod_name) + sum(rate(container_network_transmit_errors_total{job=\"${container_job}\", service=\"${container_service}\", namespace=\"${namespace}\"}[${rate}])) by (pod_name) + sum(rate(container_network_transmit_packets_dropped_total{job=\"${container_job}\", service=\"${container_service}\", namespace=\"${namespace}\"}[${rate}])) by (pod_name)",
     "legendFormat": "{{pod_name}}"
    }
   ]
  },
  {
   "title": "Aggregate Network Errors",
   "type": "singlestat",
   "gridPos": { "h": 6, "w": 4, "x": 20, "y": 12 },
   "format": "short",
   "valueName": "current",
   "targets": [
    {
     "expr": "sum(rate(container_network_receive_errors_total{job=\"${container_job}\", service=\"${container_service}\", namespace=\"${namespace}\"}[${rate}]) + rate(container_network_receive_packets_dropped_total{job=\"${container_job}\", service=\"${container_service}\", namespace=\"${namespace}\"}[${rate}]) + rate(container_network_transmit_errors_total{job=\"${container_job}\", service=\"${container_service}\", namespace=\"${namespace}\"}[${rate}]) + rate(container_network_transmit_packets_dropped_total{job=\"${container_job}\", service=\"${container_service}\", namespace=\"${namespace}\"}[${rate}]))"
    }
   ]
  }
 ]
}