###################################################################################################

httpPort: 9200

###################################################################################################

replicas: 1

###################################################################################################

fsGroup: 1000
runAsUser: 1000

###################################################################################################

podLabels:

###################################################################################################

cpuMinimum:
cpuMaximum:

###################################################################################################

memoryMinimum:
memoryMaximum:

###################################################################################################

transportPort: 9300

###################################################################################################

podAnnotations:

###################################################################################################

podTolerations:

###################################################################################################

imageTag: 6.2.3
imageName: docker.elastic.co/elasticsearch/elasticsearch-oss
imagePullPolicy: IfNotPresent

###################################################################################################

podNodeSelector:

###################################################################################################

podVolumes:
podVolumeMounts:

###################################################################################################

apiVersionService: v1
apiVersionConfigMap: v1
apiVersionDeployment: apps/v1
apiVersionStatefulSet: apps/v1

###################################################################################################

allowPrivilegeEscalation: false

###################################################################################################

podAntiAffinity: required
podAntiAffinityWeight: 100
podAntiAffinityTopologyKey: kubernetes.io/hostname

###################################################################################################

serviceType: LoadBalancer
serviceAnnotations:
serviceAwsInternalLoadBalancer: true
serviceGcpInternalLoadBalancer: true

###################################################################################################

livenessProbePeriodSeconds: 5
livenessProbeTimeoutSeconds: 1
livenessProbeSuccessThreshold: 1
livenessProbeFailureThreshold: 3
livenessProbeInitialDelaySeconds: 30

###################################################################################################

readinessProbePeriodSeconds: 5
readinessProbeTimeoutSeconds: 1
readinessProbeSuccessThreshold: 1
readinessProbeFailureThreshold: 3

###################################################################################################
###################################################################################################
###################################################################################################

# configPathData:                           path.data
# configPathLogs:                           path.logs
configNetworkHost: _local:ipv4_,_site:ipv4_
configNetworkTcpNoDelay: true
configNetworkTcpKeepAlive: true
configTransportTcpCompress: false
configTransportPingSchedule: 5s
configTransportTcpConnectTimeout: 30s

# ES_JAVA_OPTS="${ES_JAVA_OPTS} -Xms4000m -Xmx4000m"

# https://github.com/pires/kubernetes-elasticsearch-cluster
# https://github.com/clockworksoul/helm-elasticsearch

# https://www.elastic.co/guide/en/elasticsearch/reference/current/modules-node.html
# node.data: true
# node.client: true
# node.ingest: true
# node.master: true

# _cluster/health?local=true

###################################################################################################
###################################################################################################
###################################################################################################
