###################################################################################################

dataReplicas: 2

dataConfigNodeData: true
dataConfigNodeIngest: false
dataConfigNodeMaster: false

###################################################################################################

ingestReplicas: 1

ingestConfigNodeData: false
ingestConfigNodeIngest: true
ingestConfigNodeMaster: false

ingestServiceType: LoadBalancer
ingestServiceAnnotations:
ingestServiceAwsInternalLoadBalancer: true
ingestServiceGcpInternalLoadBalancer: true

###################################################################################################

masterReplicas: 3

masterConfigNodeData: false
masterConfigNodeIngest: false
masterConfigNodeMaster: true

###################################################################################################
###################################################################################################
###################################################################################################

httpPort: 9200

###################################################################################################

replicas: 3

###################################################################################################

fsGroup: 1000
runAsUser: 1000

###################################################################################################

podLabels:

###################################################################################################

cpu:
cpuMinimum: 100m
cpuMaximum: 1

###################################################################################################

clusterPort: 9300

###################################################################################################

jvmWord: jvm
dataWord: data
httpWord: http
logsWord: logs
log4jWord: log4j
configWord: config
ingestWord: ingest
masterWord: master
clusterWord: cluster

###################################################################################################

memory:
memoryMinimum:
memoryMaximum:

###################################################################################################

podAnnotations:

###################################################################################################

podTolerations:

###################################################################################################

imageTag: 6.2.3
imageName: docker.elastic.co/elasticsearch/elasticsearch-oss
imagePullPolicy: IfNotPresent

###################################################################################################

podNodeSelector:

###################################################################################################

podVolumes:
podVolumeMounts:

###################################################################################################

volumeMountBase: /usr/share/elasticsearch

###################################################################################################

volumeDataSize: 1Gi
volumeDataMode: ReadWriteOnce
volumeDataClass: anything
volumeDataEnabled: true

###################################################################################################

volumeLogsSize: 5Gi
volumeLogsMode: ReadWriteOnce
volumeLogsClass: anything
volumeLogsEnabled: true

###################################################################################################

readinessProbeLocal: true
readinessProbeStatus: yellow
readinessProbeHttpPath: _cluster/health?local={{ .Values.readinessProbeLocal }}&wait_for_status={{ .Values.readinessProbeStatus }}&timeout={{ .Values.readinessProbeTimeoutSeconds }}s

###################################################################################################

allowPrivilegeEscalation: false

###################################################################################################

clusterPodMaxUnavailable: 1

###################################################################################################

podAntiAffinity: required
podAntiAffinityWeight: 100
podAntiAffinityTopologyKey: kubernetes.io/hostname

###################################################################################################

apiVersionService: v1
apiVersionConfigMap: v1
apiVersionDeployment: apps/v1
apiVersionStatefulSet: apps/v1
apiVersionNetworkPolicy: networking.k8s.io/v1
apiVersionPodDisruptionBudget: policy/v1beta1

###################################################################################################

readinessProbePeriodSeconds: 5
readinessProbeTimeoutSeconds: 3
readinessProbeSuccessThreshold: 1
readinessProbeFailureThreshold: 3

###################################################################################################

configFile: elasticsearch.yml
configProcessors: 1
configNetworkHost: _local:ipv4_,_site:ipv4_
configNetworkTcpNoDelay:
configNetworkTcpKeepAlive:
configTransportTcpCompress:
configTransportPingSchedule:
configTransportTcpConnectTimeout:

###################################################################################################

livenessProbePeriodSeconds: 5
livenessProbeTimeoutSeconds: 3
livenessProbeSuccessThreshold: 1
livenessProbeFailureThreshold: 3
livenessProbeInitialDelaySeconds: 240

###################################################################################################

jvmFile: jvm.options
jvmHeapSize:
jvmGcLogFile: gc.log
jvmGcLogFiles: 10
jvmFileEncoding: UTF-8
jvmGcLogFileSize: 128m
jvmThreadStackSize: 1m
jmvCmsInitiatingOccupancyFraction: 75

###################################################################################################

log4jFile: log4j2.properties
log4jStatus: info
log4jRootLevel: info
log4jAppenderLayoutPattern: '[%d{ISO8601}][%-5p][%-25c{1.}] %marker%m%n'
log4jRollingRandomAccessFiles: 10
log4jRollingRandomAccessFileName: es.log
log4jRollingRandomAccessFileSize: 256MB
log4jRollingRandomAccessFilePattern: es.log.%i.gz
log4jRollingRandomAccessFileBufferSize:
log4jRollingRandomAccessFilePermissions:
log4jRollingRandomAccessFileImmediateFlush:

###################################################################################################
