###################################################################################################
###################################################################################################

httpPort: 9200

###################################################################################################

fsGroup: 1000
runAsUser: 1000

###################################################################################################

dataWord: data
httpWord: http
logsWord: logs
configWord: config
ingestWord: ingest
masterWord: master
clusterWord: cluster

###################################################################################################

clusterPort: 9300

###################################################################################################

jvmFile: jvm.options
jvmGcLogFile: gc.log

###################################################################################################

maxUnavailable: 1

###################################################################################################

configFile: elasticsearch.yml
configMountBase: /usr/share/elasticsearch

###################################################################################################

volumeMountBase: /state

###################################################################################################

imageTag: 6.2.3
imageName: docker.elastic.co/elasticsearch/elasticsearch-oss
imagePullPolicy: IfNotPresent

###################################################################################################

readinessProbeHttpPath: _cluster/health?local=true&wait_for_status=yellow&timeout=1s

###################################################################################################

log4jFile: log4j2.properties
log4jFileName: es.log
log4jFilePattern: es.log.%i.gz
log4jAppenderLayoutPattern: '[%d{ISO8601}][%-5p][%-25c{1.}] %marker%m%n'

###################################################################################################

apiVersionService: v1
apiVersionConfigMap: v1
apiVersionStatefulSet: apps/v1
apiVersionNetworkPolicy: networking.k8s.io/v1
apiVersionPodDisruptionBudget: policy/v1beta1

###################################################################################################
###################################################################################################

dataReplicas: 3

###################################################################################################

dataPodLabels:

###################################################################################################

dataCpu:
dataCpuMinimum: 100m
dataCpuMaximum: 1

###################################################################################################

dataMemory:
dataMemoryMinimum: 1024Mi
dataMemoryMaximum: 1024Mi

###################################################################################################

dataVolumeMode: ReadWriteOnce
dataVolumeName: state
dataVolumeSize: 25Gi
dataVolumeClass: anything
dataVolumeEnabled: true

###################################################################################################

dataPodAnnotations:

###################################################################################################

dataPodTolerations:

###################################################################################################

dataPodNodeSelector:

###################################################################################################

dataPodVolumes:
dataPodVolumeMounts:

###################################################################################################

dataConfigNodeData: true
dataConfigNodeIngest: false
dataConfigNodeMaster: false
dataConfigProcessors: 1
dataConfigNetworkHost: _local:ipv4_,_site:ipv4_

###################################################################################################

dataJvmHeapSize: 768m
dataJvmGcLogFiles: 10
dataJvmGcLogFileSize: 128m
dataJvmThreadStackSize: 1m

###################################################################################################

dataLog4jFiles: 10
dataLog4jStatus: info
dataLog4jFileSize: 256MB
dataLog4jRootLevel: info
dataLog4jImmediateFlush: false

###################################################################################################

dataAllowPrivilegeEscalation: false

###################################################################################################

dataPodAntiAffinity: required
dataPodAntiAffinityWeight: 100
dataPodAntiAffinityTopologyKey: kubernetes.io/hostname

###################################################################################################

dataReadinessProbePeriodSeconds: 5
dataReadinessProbeTimeoutSeconds: 3
dataReadinessProbeSuccessThreshold: 1
dataReadinessProbeFailureThreshold: 3

###################################################################################################

dataLivenessProbePeriodSeconds: 5
dataLivenessProbeTimeoutSeconds: 3
dataLivenessProbeSuccessThreshold: 1
dataLivenessProbeFailureThreshold: 3
dataLivenessProbeInitialDelaySeconds: 240

###################################################################################################
###################################################################################################

ingestReplicas: 3

###################################################################################################

ingestPodLabels:

###################################################################################################

ingestCpu:
ingestCpuMinimum: 100m
ingestCpuMaximum: 1

###################################################################################################

ingestMemory:
ingestMemoryMinimum: 1024Mi
ingestMemoryMaximum: 1024Mi

###################################################################################################

ingestVolumeMode: ReadWriteOnce
ingestVolumeName: state
ingestVolumeSize: 5Gi
ingestVolumeClass: anything
ingestVolumeEnabled: true

###################################################################################################

ingestPodAnnotations:

###################################################################################################

ingestPodTolerations:

###################################################################################################

ingestPodNodeSelector:

###################################################################################################

ingestPodVolumes:
ingestPodVolumeMounts:

###################################################################################################

ingestConfigNodeData: false
ingestConfigNodeIngest: true
ingestConfigNodeMaster: false
ingestConfigProcessors: 1
ingestConfigNetworkHost: _local:ipv4_,_site:ipv4_

###################################################################################################

ingestJvmHeapSize: 768m
ingestJvmGcLogFiles: 10
ingestJvmGcLogFileSize: 128m
ingestJvmThreadStackSize: 1m

###################################################################################################

ingestLog4jFiles: 10
ingestLog4jStatus: info
ingestLog4jFileSize: 256MB
ingestLog4jRootLevel: info
ingestLog4jImmediateFlush: false

###################################################################################################

ingestAllowPrivilegeEscalation: false

###################################################################################################

ingestPodAntiAffinity: required
ingestPodAntiAffinityWeight: 100
ingestPodAntiAffinityTopologyKey: kubernetes.io/hostname

###################################################################################################

ingestReadinessProbePeriodSeconds: 5
ingestReadinessProbeTimeoutSeconds: 3
ingestReadinessProbeSuccessThreshold: 1
ingestReadinessProbeFailureThreshold: 3

###################################################################################################

ingestServiceType: LoadBalancer
ingestServiceAnnotations:
ingestServiceAwsInternalLoadBalancer: true
ingestServiceGcpInternalLoadBalancer: true

###################################################################################################

ingestLivenessProbePeriodSeconds: 5
ingestLivenessProbeTimeoutSeconds: 3
ingestLivenessProbeSuccessThreshold: 1
ingestLivenessProbeFailureThreshold: 3
ingestLivenessProbeInitialDelaySeconds: 240

###################################################################################################
###################################################################################################

masterReplicas: 3

###################################################################################################

masterPodLabels:

###################################################################################################

masterCpu:
masterCpuMinimum: 100m
masterCpuMaximum: 1

###################################################################################################

masterMemory:
masterMemoryMinimum: 1024Mi
masterMemoryMaximum: 1024Mi

###################################################################################################

masterVolumeMode: ReadWriteOnce
masterVolumeName: state
masterVolumeSize: 5Gi
masterVolumeClass: anything
masterVolumeEnabled: true

###################################################################################################

masterPodAnnotations:

###################################################################################################

masterPodTolerations:

###################################################################################################

masterPodNodeSelector:

###################################################################################################

masterPodVolumes:
masterPodVolumeMounts:

###################################################################################################

masterConfigNodeData: false
masterConfigNodeIngest: false
masterConfigNodeMaster: true
masterConfigProcessors: 1
masterConfigNetworkHost: _local:ipv4_,_site:ipv4_

###################################################################################################

masterJvmHeapSize: 768m
masterJvmGcLogFiles: 10
masterJvmGcLogFileSize: 128m
masterJvmThreadStackSize: 1m

###################################################################################################

masterLog4jFiles: 10
masterLog4jStatus: info
masterLog4jFileSize: 256MB
masterLog4jRootLevel: info
masterLog4jImmediateFlush: false

###################################################################################################

masterAllowPrivilegeEscalation: false

###################################################################################################

masterPodAntiAffinity: required
masterPodAntiAffinityWeight: 100
masterPodAntiAffinityTopologyKey: kubernetes.io/hostname

###################################################################################################

masterReadinessProbePeriodSeconds: 5
masterReadinessProbeTimeoutSeconds: 3
masterReadinessProbeSuccessThreshold: 1
masterReadinessProbeFailureThreshold: 3

###################################################################################################

masterLivenessProbePeriodSeconds: 5
masterLivenessProbeTimeoutSeconds: 3
masterLivenessProbeSuccessThreshold: 1
masterLivenessProbeFailureThreshold: 3
masterLivenessProbeInitialDelaySeconds: 240

###################################################################################################
###################################################################################################
