###################################################################################################

fsGroup: 1000
runAsUser: 1000

###################################################################################################

httpPort: 9200

###################################################################################################

podLabels:

###################################################################################################

cpuMinimum:
cpuMaximum:

###################################################################################################

memoryMinimum:
memoryMaximum:

###################################################################################################

transportPort: 9300

###################################################################################################

podAnnotations:

###################################################################################################

podTolerations:

###################################################################################################

imageTag: 6.2.3
imageName: docker.elastic.co/elasticsearch/elasticsearch-oss
imagePullPolicy: IfNotPresent

###################################################################################################

podNodeSelector:

###################################################################################################

podVolumes:
podVolumeMounts:

###################################################################################################

apiVersionService: v1
apiVersionConfigMap: v1
apiVersionDeployment: apps/v1
apiVersionStatefulSet: apps/v1

###################################################################################################

allowPrivilegeEscalation: false

###################################################################################################

podAntiAffinityWeight: 100
podAntiAffinityTopologyKey: kubernetes.io/hostname

###################################################################################################

serviceType: LoadBalancer
serviceAnnotations:
serviceAwsInternalLoadBalancer: true
serviceGcpInternalLoadBalancer: true

###################################################################################################

livenessProbePeriodSeconds: 5
livenessProbeTimeoutSeconds: 1
livenessProbeSuccessThreshold: 1
livenessProbeFailureThreshold: 3
livenessProbeInitialDelaySeconds: 30

###################################################################################################

readinessProbePeriodSeconds: 5
readinessProbeTimeoutSeconds: 1
readinessProbeSuccessThreshold: 1
readinessProbeFailureThreshold: 3

###################################################################################################
