###################################################################################################

httpName: http
httpPort: 9200

###################################################################################################

replicas: 3

###################################################################################################

fsGroup: 1000
runAsUser: 1000

###################################################################################################

podLabels:

###################################################################################################

cpuMinimum:
cpuMaximum:

###################################################################################################

memoryMinimum:
memoryMaximum:

###################################################################################################

transportName: transport
transportPort: 9300

###################################################################################################

podAnnotations:

###################################################################################################

podTolerations:

###################################################################################################

imageTag: 6.2.3
imageName: docker.elastic.co/elasticsearch/elasticsearch-oss
imagePullPolicy: IfNotPresent

###################################################################################################

podNodeSelector:

###################################################################################################

podVolumes:
podVolumeMounts:

###################################################################################################

volumeMountBase: /usr/share/elasticsearch

###################################################################################################

podMinAvailable:
podMaxUnavailable: 1

###################################################################################################

volumeDataName: data
volumeDataSize: 10Gi
volumeDataMode: ReadWriteOnce
volumeDataClass: anything
volumeDataEnabled: true

###################################################################################################

volumeLogsName: logs
volumeLogsSize: 5Gi
volumeLogsMode: ReadWriteOnce
volumeLogsClass: anything
volumeLogsEnabled: true

###################################################################################################

allowPrivilegeEscalation: false

###################################################################################################

podAntiAffinity: required
podAntiAffinityWeight: 100
podAntiAffinityTopologyKey: kubernetes.io/hostname

###################################################################################################

apiVersionService: v1
apiVersionConfigMap: v1
apiVersionDeployment: apps/v1
apiVersionStatefulSet: apps/v1
apiVersionNetworkPolicy: networking.k8s.io/v1
apiVersionPodDisruptionBudget: policy/v1beta1

###################################################################################################

readinessProbePeriodSeconds: 5
readinessProbeTimeoutSeconds: 1
readinessProbeSuccessThreshold: 1
readinessProbeFailureThreshold: 3

###################################################################################################

serviceType: LoadBalancer
serviceAnnotations:
serviceAwsInternalLoadBalancer: true
serviceGcpInternalLoadBalancer: true

###################################################################################################

configFile: elasticsearch.yml
configName: config
configNodeData: false
configNodeIngest: false
configNodeMaster: true
configProcessors: 1
configNetworkHost: _local:ipv4_,_site:ipv4_
configNetworkTcpNoDelay:
configNetworkTcpKeepAlive:
configTransportTcpCompress:
configTransportPingSchedule:
configTransportTcpConnectTimeout:

###################################################################################################

livenessProbePeriodSeconds: 5
livenessProbeTimeoutSeconds: 1
livenessProbeSuccessThreshold: 1
livenessProbeFailureThreshold: 3
livenessProbeInitialDelaySeconds: 10

###################################################################################################

jvmFile: jvm.options
jvmName: jvm
jvmHeapSize: 1g
jvmGcLogFile: gc.log
jvmGcLogFiles: 10
jvmFileEncoding: UTF-8
jvmGcLogFileSize: 128m
jvmThreadStackSize: 1m
jmvCmsInitiatingOccupancyFraction: 75

###################################################################################################

log4jFile: log4j2.properties
log4jName: log4j
log4jStatus: info
log4jRootLevel: info
log4jAppenderLayoutPattern: '[%d{ISO8601}][%-5p][%-25c{1.}] %marker%m%n'
log4jRollingRandomAccessFiles: 10
log4jRollingRandomAccessFileName: es.log
log4jRollingRandomAccessFileSize: 256MB
log4jRollingRandomAccessFilePattern: es.log.%i.gz
log4jRollingRandomAccessFileBufferSize: 262144
log4jRollingRandomAccessFilePermissions: rw-rw-r--
log4jRollingRandomAccessFileImmediateFlush: false

###################################################################################################
