###################################################################################################

coreDns:
  enabled: false

###################################################################################################

kubeDns:
  enabled: true

###################################################################################################

grafana:
  ingress:
    hosts: [ grafana.monitoring.sandpit.fkaj.com ]
    enabled: true
    annotations:
      kubernetes.io/ingress.class: nginx
      certmanager.k8s.io/cluster-issuer: cluster-issuer-lets-encrypt
      certmanager.k8s.io/acme-challenge-type: dns01
      certmanager.k8s.io/acme-dns01-provider: route53

###################################################################################################

prometheus:
  ingress:
    hosts: [ prometheus.monitoring.sandpit.fkaj.com ]
    enabled: true
    annotations:
      kubernetes.io/ingress.class: nginx
      certmanager.k8s.io/cluster-issuer: cluster-issuer-lets-encrypt
      certmanager.k8s.io/acme-challenge-type: dns01
      certmanager.k8s.io/acme-dns01-provider: route53
  prometheusSpec:
    logLevel: debug
    replicas: 3
  podDisruptionBudget:
    enabled: true

###################################################################################################

alertmanager:
  ingress:
    hosts: [ alertmanager.monitoring.sandpit.fkaj.com ]
    enabled: true
    annotations:
      kubernetes.io/ingress.class: nginx
      certmanager.k8s.io/cluster-issuer: cluster-issuer-lets-encrypt
      certmanager.k8s.io/acme-challenge-type: dns01
      certmanager.k8s.io/acme-dns01-provider: route53
  alertmanagerSpec:
    logLevel: debug
    replicas: 3
  podDisruptionBudget:
    enabled: true

###################################################################################################
