###################################################################################################

kind: Service
apiVersion: "{{ .Values.apiVersionService }}"
metadata:
  name: "{{ template "XXXXName" . }}"
  namespace: "{{ template "XXXXNamespace" . }}"
  labels:
    name: "{{ template "XXXXName" . }}"
    chart: "{{ template "XXXXChart" . }}"
    release: "{{ template "XXXXRelease" . }}"
    heritage: "{{ template "XXXXHeritage" . }}"
  {{- if or .Values.serviceAnnotations (and (eq .Values.serviceType "LoadBalancer") (or .Values.serviceAwsInternalLoadBalancer .Values.serviceGcpInternalLoadBalancer)) }}
  annotations:
    {{- if .Values.serviceAwsInternalLoadBalancer }}
    service.beta.kubernetes.io/aws-load-balancer-internal: "true"
    {{- end }}
    {{- if .Values.serviceGcpInternalLoadBalancer }}
    cloud.google.com/load-balancer-type: Internal
    {{- end }}
    {{- if .Values.serviceAnnotations }}
{{ toYaml .Values.serviceAnnotations | indent 4 }}
    {{- end }}
  {{- end }}
spec:
  type: "{{ .Values.serviceType }}"
  selector:
    name: "{{ template "XXXXName" . }}"
  ports:
    - name: "{{ template "XXXXChart" . }}"
      port: {{ .Values.servicePort }}
      targetPort: "{{ template "XXXXChart" . }}"

###################################################################################################
