###################################################################################################

aws:
  region: eu-west-1
  zoneType: public
  accessKey: AKIAIKVY7OEOV636XIMQ
  secretKey:

###################################################################################################

rbac:
  create: true

###################################################################################################

policy: sync

###################################################################################################
