###################################################################################################

kind: ConfigMap
apiVersion: "{{ .Values.apiVersionConfigMap }}"
metadata:
  name: "{{ template "filebeatName" . }}"
  namespace: "{{ template "filebeatNamespace" . }}"
  labels:
    name: "{{ template "filebeatName" . }}"
    chart: "{{ template "filebeatChart" . }}"
    release: "{{ template "filebeatRelease" . }}"
    heritage: "{{ template "filebeatHeritage" . }}"
data:
  {{ .Values.configFile }}: |
    path.data: "{{ .Values.configDataPath }}"
    path.logs: "{{ .Values.configLogsPath }}"

    logging.level: "{{ .Values.configLoggingLevel }}"
    logging.metrics.period: "{{ .Values.configLoggingMetricsPeriod }}"
    logging.metrics.enabled: {{ .Values.configLoggingMetricsEnabled }}

    setup.kibana:
      host: "kibana001-kibana.default.svc:80"

    filebeat.prospectors:
      multiline.pattern: '^[[:space:]]+(at|\.{3})\b|^Caused by:'
      multiline.negate: false
      multiline.match: "after"

    filebeat.prospectors:
      - type: "docker"
        processors:
          - add_kubernetes_metadata:
              in_cluster: true
        containers.ids:
          - "*"

    {{- if or .Values.configLocaleProcessorEnabled .Values.configCloudMetadataProcessorEnabled .Values.configDecodeJsonProcessorEnabled }}
    processors:
      {{- if .Values.configLocaleProcessorEnabled }}
      - add_locale:
      {{- end }}
      {{- if .Values.configCloudMetadataProcessorEnabled }}
      - add_cloud_metadata:
      {{- end }}
      {{- if .Values.configDecodeJsonProcessorEnabled }}
      - decode_json_fields:
          fields: [ "{{ .Values.configDecodeJsonProcessorField }}" ]
          target: "{{ .Values.configDecodeJsonProcessorTarget }}"
          max_depth: {{ .Values.configDecodeJsonProcessorMaxDepth }}
          process_array: {{ .Values.configDecodeJsonProcessorProcessArray }}
      {{- end }}
    {{- end }}

    queue:
      mem:
        events: 8192

    output.elasticsearch:
      hosts: [ "elasticsearch-elasticsearch-ingest.logging.svc:80" ]
      worker: 16
      bulk_max_size: 1024
      compression_level: 1

###################################################################################################
