###################################################################################################

kind: ConfigMap
apiVersion: "{{ .Values.apiVersionConfigMap }}"
metadata:
  name: "{{ template "filebeatName" . }}"
  namespace: "{{ template "filebeatNamespace" . }}"
  labels:
    name: "{{ template "filebeatName" . }}"
    chart: "{{ template "filebeatChart" . }}"
    release: "{{ template "filebeatRelease" . }}"
    heritage: "{{ template "filebeatHeritage" . }}"
data:
  {{ .Values.configFile }}: |
    filebeat.config:
      modules:
        path: "${path.config}/modules.d/*.yml"

    path.data: /var/log
    path.logs: /var/log

    logging.level: "info"
    logging.metrics.enabled: true
    logging.metrics.period: "60s"

    setup.kibana:
      host: "kibana001-kibana.default.svc:80"

    filebeat.prospectors:
      multiline.pattern: '^[[:space:]]+(at|\.{3})\b|^Caused by:'
      multiline.negate: false
      multiline.match: "after"

    filebeat.prospectors:
      - type: "docker"
        processors:
          - add_kubernetes_metadata:
              in_cluster: true
        containers.ids:
          - "*"

    processors:
      - add_locale:
      - add_cloud_metadata:
      - decode_json_fields:
          fields: [ "message" ]
          target: "payload"
          max_depth: 10
          process_array: true

    queue:
      mem:
        events: 8192

    output.elasticsearch:
      hosts: [ "elasticsearch-elasticsearch-ingest.logging.svc:80" ]
      worker: 16
      bulk_max_size: 1024
      compression_level: 1

###################################################################################################
