###################################################################################################

kind: ConfigMap
apiVersion: "{{ .Values.apiVersionConfigMap }}"
metadata:
  name: "{{ template "filebeatName" . }}"
  namespace: "{{ template "filebeatNamespace" . }}"
  labels:
    name: "{{ template "filebeatName" . }}"
    chart: "{{ template "filebeatChart" . }}"
    release: "{{ template "filebeatRelease" . }}"
    heritage: "{{ template "filebeatHeritage" . }}"
data:
  {{ .Values.configFile }}: |
    path.data: "{{ .Values.configPathData }}"
    path.logs: "{{ .Values.configPathLogs }}"
    logging.level: "{{ .Values.configLoggingLevel }}"
    logging.to_files: false
    logging.to_syslog: false
    {{- if .Values.configSetupKibanaHost }}
    setup.kibana.host: "{{ .Values.configSetupKibanaHost }}"
    {{- end }}
    logging.metrics.period: "{{ .Values.configLoggingMetricsPeriod }}"
    logging.metrics.enabled: {{ .Values.configLoggingMetricsEnabled }}
    filebeat.prospectors:
      - type: docker
        {{- if or .Values.configFilebeatProspectorsDockerProcessorsAddKubernetesMetadataEnabled .Values.configFilebeatProspectorsDockerProcessorsDecodeJsonFieldsEnabled }}
        processors:
          {{- if .Values.configFilebeatProspectorsDockerProcessorsAddKubernetesMetadataEnabled }}
          - add_kubernetes_metadata:
              in_cluster: true
          {{- end }}
          {{- if .Values.configFilebeatProspectorsDockerProcessorsDecodeJsonFieldsEnabled }}
          - decode_json_fields:
              fields: [ "{{ .Values.configFilebeatProspectorsDockerProcessorsDecodeJsonFieldsField }}" ]
              target: "{{ .Values.configFilebeatProspectorsDockerProcessorsDecodeJsonFieldsTarget }}"
              max_depth: {{ .Values.configFilebeatProspectorsDockerProcessorsDecodeJsonFieldsMaxDepth }}
              process_array: {{ .Values.configFilebeatProspectorsDockerProcessorsDecodeJsonFieldsProcessArray }}
              overwrite_keys: {{ .Values.configFilebeatProspectorsDockerProcessorsDecodeJsonFieldsOverwriteKeys }}
          {{- end }}
        {{- end }}
        containers.ids: [ '*' ]
        {{- if .Values.configFilebeatProspectorsDockerMultilineEnabled }}
        multiline.match: "{{ .Values.configFilebeatProspectorsDockerMultilineMatch }}"
        multiline.negate: {{ .Values.configFilebeatProspectorsDockerMultilineNegate }}
        multiline.pattern: '{{ .Values.configFilebeatProspectorsDockerMultilinePattern }}'
        {{- end }}
    {{- if or .Values.configProcessorAddLocaleEnabled .Values.configProcessorAddCloudMetadataEnabled }}
    processors:
      {{- if .Values.configProcessorAddLocaleEnabled }}
      - add_locale:
          format: "{{ .Values.configProcessorAddLocaleFormat }}"
      {{- end }}
      {{- if .Values.configProcessorAddCloudMetadataEnabled }}
      - add_cloud_metadata: ~
      {{- end }}
    {{- end }}
    output.elasticsearch.hosts: [ "{{ required ".Values.configOutputElasticsearchHost" .Values.configOutputElasticsearchHost }}" ]
    {{- if .Values.configOutputElasticsearchWorker }}
    output.elasticsearch.worker: {{ .Values.configOutputElasticsearchWorker }}
    {{- end }}
    {{- if ge (.Values.configOutputElasticsearchMaxRetries | int) 0 }}
    output.elasticsearch.max_retries: {{ .Values.configOutputElasticsearchMaxRetries }}
    {{- end }}
    {{- if .Values.configOutputElasticsearchBulkMaxSize }}
    output.elasticsearch.bulk_max_size: {{ .Values.configOutputElasticsearchBulkMaxSize }}
    {{- end }}
    {{- if .Values.configOutputElasticsearchCompressionLevel }}
    output.elasticsearch.compression_level: {{ .Values.configOutputElasticsearchCompressionLevel }}
    {{- end }}

###################################################################################################
