###################################################################################################

kind: ConfigMap
apiVersion: "{{ .Values.apiVersionConfigMap }}"
metadata:
  name: "{{ template "filebeatName" . }}"
  namespace: "{{ template "filebeatNamespace" . }}"
  labels:
    name: "{{ template "filebeatName" . }}"
    chart: "{{ template "filebeatChart" . }}"
    release: "{{ template "filebeatRelease" . }}"
    heritage: "{{ template "filebeatHeritage" . }}"
data:
  {{ .Values.configFile }}: |
    filebeat.config:
      prospectors:
        path: ${path.config}/prospectors.d/*.yml
      modules:
        path: ${path.config}/modules.d/*.yml

    logging.level: info
    logging.metrics.enabled: false

    setup.kibana:
      host: "kibana001-kibana.default.svc:80"

    filebeat.prospectors:
      multiline.pattern: '^[[:space:]]+(at|\.{3})\b|^Caused by:'
      multiline.negate: false
      multiline.match: after

    processors:
      - add_locale:
      - add_cloud_metadata:
      - decode_json_fields:
          fields: [ "message" ]
          process_array: false
          max_depth: 8
          target: "json_message"
          overwrite_keys: false

    output.elasticsearch:
      hosts: [ 'elasticsearch001-elasticsearch-client.default.svc:80' ]

  default.yml: |
    - type: docker
      containers.ids:
      - "*"
      processors:
        - add_kubernetes_metadata:
            in_cluster: true

###################################################################################################
