###################################################################################################

kind: PodDisruptionBudget
apiVersion: "{{ .Values.apiVersionPodDisruptionBudget }}"
metadata:
  name: "{{ template "elasticsearchClusterName" . }}"
  namespace: "{{ template "elasticsearchNamespace" . }}"
  labels:
    name: "{{ template "elasticsearchClusterName" . }}"
    chart: "{{ template "elasticsearchChart" . }}"
    release: "{{ template "elasticsearchRelease" . }}"
    heritage: "{{ template "elasticsearchHeritage" . }}"
spec:
  selector:
    matchLabels:
      chart: "{{ template "elasticsearchChart" . }}"
      release: "{{ template "elasticsearchRelease" . }}"
      heritage: "{{ template "elasticsearchHeritage" . }}"
  {{- if .Values.clusterPodMinAvailable }}
  minAvailable: {{ .Values.clusterPodMinAvailable }}
  {{- else }}
  maxUnavailable: {{ .Values.clusterPodMaxUnavailable }}
  {{- end }}

###################################################################################################
