###################################################################################################

kind: ConfigMap
apiVersion: "{{ .Values.apiVersionConfigMap }}"
metadata:
  name: "{{ template "elasticsearchName" . }}"
  namespace: "{{ template "elasticsearchNamespace" . }}"
  labels:
    name: "{{ template "elasticsearchName" . }}"
    chart: "{{ template "elasticsearchChart" . }}"
    release: "{{ template "elasticsearchRelease" . }}"
    heritage: "{{ template "elasticsearchHeritage" . }}"
data:
  "{{ .Values.configFile }}": |
    http.port: "{{ .Values.httpPort }}"
    path.data: "{{ template "elasticsearchVolumeDataMount" . }}"
    path.logs: "{{ template "elasticsearchVolumeLogsMount" . }}"
    cluster.name: "{{ template "elasticsearchName" . }}"
    network.host: "{{ .Values.configNetworkHost }}"
    transport.tcp.port: "{{ .Values.transportPort }}"
    network.tcp.no_delay: "{{ .Values.configNetworkTcpNoDelay }}"
    network.tcp.keep_alive: "{{ .Values.configNetworkTcpKeepAlive }}"
    transport.tcp.compress: "{{ .Values.configTransportTcpCompress }}"
    transport.ping_schedule: "{{ .Values.configTransportPingSchedule }}"
    transport.tcp.connect_timeout: "{{ .Values.configTransportTcpConnectTimeout }}"
    discovery.zen.ping.unicast.hosts: "{{ template "elasticsearchName" . }}"
    discovery.zen.minimum_master_nodes: "{{ template "elasticsearchMinimumMasterNodes" . }}"

###################################################################################################
