###################################################################################################

kind: StatefulSet
apiVersion: "{{ .Values.apiVersionStatefulSet }}"
metadata:
  name: "{{ template "elasticsearchDataName" . }}"
  namespace: "{{ template "elasticsearchNamespace" . }}"
  labels:
    name: "{{ template "elasticsearchDataName" . }}"
    chart: "{{ template "elasticsearchChart" . }}"
    release: "{{ template "elasticsearchRelease" . }}"
    heritage: "{{ template "elasticsearchHeritage" . }}"
    node.data: "{{ .Values.dataConfigNodeData }}"
    node.ingest: "{{ .Values.dataConfigNodeIngest }}"
    node.master: "{{ .Values.dataConfigNodeMaster }}"
  annotations:
    config.sha256sum: "{{ include (print .Template.BasePath "/data-config-map.yaml") . | sha256sum }}"
spec:
  selector:
    matchLabels:
      name: "{{ template "elasticsearchDataName" . }}"
  replicas: {{ .Values.dataReplicas }}
  serviceName: "{{ template "elasticsearchClusterName" . }}"
  {{- if .Values.volumeEnabled }}
  volumeClaimTemplates:
    - metadata:
        name: "{{ .Values.volumeName }}"
        annotations:
          volume.alpha.kubernetes.io/storage-class: "{{ .Values.dataVolumeClass }}"
      spec:
        resources:
          requests:
            storage: "{{ .Values.dataVolumeSize }}"
        accessModes: [ "{{ .Values.volumeMode }}" ]
  {{- end }}
  template:
    metadata:
      labels:
        name: "{{ template "elasticsearchDataName" . }}"
        chart: "{{ template "elasticsearchChart" . }}"
        release: "{{ template "elasticsearchRelease" . }}"
        heritage: "{{ template "elasticsearchHeritage" . }}"
        node.data: "{{ .Values.dataConfigNodeData }}"
        node.ingest: "{{ .Values.dataConfigNodeIngest }}"
        node.master: "{{ .Values.dataConfigNodeMaster }}"
        {{- if .Values.podLabels }}
{{ toYaml .Values.podLabels | indent 8 }}
        {{- end }}
      {{- if .Values.podAnnotations }}
      annotations:
{{ toYaml .Values.podAnnotations | indent 8 }}
      {{- end }}
    spec:
      affinity:
        podAntiAffinity:
          {{- if eq (.Values.podAntiAffinity | lower) "required" }}
          requiredDuringSchedulingIgnoredDuringExecution:
            - topologyKey: "{{ .Values.podAntiAffinityTopologyKey }}"
              labelSelector:
                matchExpressions:
                  - key: name
                    values: [ "{{ template "elasticsearchDataName" . }}" ]
                    operator: In
          {{- else }}
          preferredDuringSchedulingIgnoredDuringExecution:
            - weight: {{ .Values.podAntiAffinityWeight }}
              podAffinityTerm:
                topologyKey: "{{ .Values.podAntiAffinityTopologyKey }}"
                labelSelector:
                  matchExpressions:
                    - key: name
                      values: [ "{{ template "elasticsearchDataName" . }}" ]
                      operator: In
          {{- end }}
      {{- if or (ge (default 0 (.Values.fsGroup | int)) 0) (ge (default 0 (.Values.runAsUser | int)) 0) }}
      securityContext:
        {{- if ge (default 0 (.Values.fsGroup | int)) 0 }}
        fsGroup: {{ .Values.fsGroup }}
        {{- end }}
        {{- if ge (default 0 (.Values.runAsUser | int)) 0 }}
        runAsUser: {{ .Values.runAsUser }}
        {{- end }}
      {{- end }}
      {{- if .Values.podNodeSelector }}
      nodeSelector:
{{ toYaml .Values.podNodeSelector | indent 8 }}
      {{- end }}
      {{- if .Values.podTolerations }}
      tolerations:
{{ toYaml .Values.podTolerations | indent 8 }}
      {{- end }}
      volumes:
        - name: "{{ .Values.configWord }}"
          configMap:
            name: "{{ template "elasticsearchDataName" . }}"
        {{- if not .Values.volumeEnabled }}
        - name: "{{ .Values.volumeName }}"
          emptyDir: {}
        {{- end }}
      {{- if .Values.podVolumes }}
{{ toYaml .Values.podVolumes | indent 8 }}
      {{- end }}
      initContainers:
        - name: init
          image: "{{ template "elasticsearchImage" . }}"
          imagePullPolicy: "{{ .Values.imagePullPolicy }}"
          securityContext:
            runAsUser: 0
            allowPrivilegeEscalation: {{ .Values.allowPrivilegeEscalation }}
          command:
            - /bin/bash
            - -c
            - mkdir -pv {{ template "elasticsearchDataBase" . }} &&
              mkdir -pv {{ template "elasticsearchLogsBase" . }} &&
              chown -cR {{ .Values.runAsUser }}:{{ .Values.fsGroup }} {{ template "elasticsearchDataBase" . }} &&
              chown -cR {{ .Values.runAsUser }}:{{ .Values.fsGroup }} {{ template "elasticsearchLogsBase" . }}
          volumeMounts:
            - name: "{{ .Values.volumeName }}"
              mountPath: "{{ .Values.volumeMountBase }}"
      containers:
        - name: "{{ .Chart.Name }}"
          image: "{{ template "elasticsearchImage" . }}"
          imagePullPolicy: "{{ .Values.imagePullPolicy }}"
          securityContext:
            allowPrivilegeEscalation: {{ .Values.allowPrivilegeEscalation }}
          env:
            - name: node.name
              valueFrom:
                fieldRef:
                  fieldPath: metadata.name
          ports:
            - name: "{{ .Values.httpWord }}"
              containerPort: {{ .Values.httpPort }}
            - name: "{{ .Values.clusterWord }}"
              containerPort: {{ .Values.clusterPort }}
          {{- if or .Values.dataCpu .Values.dataCpuMinimum .Values.dataCpuMaximum .Values.dataMemory .Values.dataMemoryMinimum .Values.dataMemoryMaximum }}
          resources:
            {{- if or .Values.dataCpu .Values.dataCpuMinimum .Values.dataMemory .Values.dataMemoryMinimum }}
            requests:
              {{- if or .Values.dataCpu .Values.dataCpuMinimum }}
              cpu: "{{ if .Values.dataCpu }}{{ .Values.dataCpu }}{{ else }}{{ .Values.dataCpuMinimum }}{{ end }}"
              {{- end }}
              {{- if or .Values.dataMemory .Values.dataMemoryMinimum }}
              memory: "{{ if .Values.dataMemory }}{{ .Values.dataMemory }}{{ else }}{{ .Values.dataMemoryMinimum }}{{ end }}"
              {{- end }}
            {{- end }}
            {{- if or .Values.dataCpu .Values.dataCpuMaximum .Values.dataMemory .Values.dataMemoryMaximum }}
            limits:
              {{- if or .Values.dataCpu .Values.dataCpuMaximum }}
              cpu: "{{ if .Values.dataCpu }}{{ .Values.dataCpu }}{{ else }}{{ .Values.dataCpuMaximum }}{{ end }}"
              {{- end }}
              {{- if or .Values.dataMemory .Values.dataMemoryMaximum }}
              memory: "{{ if .Values.dataMemory }}{{ .Values.dataMemory }}{{ else }}{{ .Values.dataMemoryMaximum }}{{ end }}"
              {{- end }}
            {{- end }}
          {{- end }}
          volumeMounts:
            - name: "{{ .Values.configWord }}"
              subPath: "{{ .Values.jvmFile }}"
              mountPath: "{{ template "elasticsearchConfigMountBase" . }}/{{ .Values.jvmFile }}"
            - name: "{{ .Values.configWord }}"
              subPath: "{{ .Values.log4jFile }}"
              mountPath: "{{ template "elasticsearchConfigMountBase" . }}/{{ .Values.log4jFile }}"
            - name: "{{ .Values.configWord }}"
              subPath: "{{ .Values.configFile }}"
              mountPath: "{{ template "elasticsearchConfigMountBase" . }}/{{ .Values.configFile }}"
            - name: "{{ .Values.volumeName }}"
              mountPath: "{{ .Values.volumeMountBase }}"
          {{- if .Values.podVolumeMounts }}
{{ toYaml .Values.podVolumeMounts | indent 12 }}
          {{- end }}
          readinessProbe:
            httpGet:
              path: "{{ .Values.readinessProbeHttpPath }}"
              port: "{{ .Values.httpWord }}"
            periodSeconds: {{ .Values.readinessProbePeriodSeconds }}
            timeoutSeconds: {{ .Values.readinessProbeTimeoutSeconds }}
            successThreshold: {{ .Values.readinessProbeSuccessThreshold }}
            failureThreshold: {{ .Values.readinessProbeFailureThreshold }}
          livenessProbe:
            tcpSocket:
              port: "{{ .Values.clusterWord }}"
            periodSeconds: {{ .Values.livenessProbePeriodSeconds }}
            timeoutSeconds: {{ .Values.livenessProbeTimeoutSeconds }}
            successThreshold: {{ .Values.livenessProbeSuccessThreshold }}
            failureThreshold: {{ .Values.livenessProbeFailureThreshold }}
            initialDelaySeconds: {{ .Values.livenessProbeInitialDelaySeconds }}

###################################################################################################
