###################################################################################################

kind: NetworkPolicy
apiVersion: "{{ .Values.apiVersionNetworkPolicy }}"
metadata:
  name: "{{ template "elasticsearchName" . }}"
  namespace: "{{ template "elasticsearchNamespace" . }}"
  labels:
    name: "{{ template "elasticsearchName" . }}"
    chart: "{{ template "elasticsearchChart" . }}"
    release: "{{ template "elasticsearchRelease" . }}"
    heritage: "{{ template "elasticsearchHeritage" . }}"
spec:
  podSelector:
    matchLabels:
      name: "{{ template "elasticsearchName" . }}"
  ingress:
    - ports:
        - port: {{ .Values.httpPort }}
        - port: {{ .Values.transportPort }}
      from:
        - podSelector:
            matchLabels:
              name: "{{ template "elasticsearchName" . }}"

###################################################################################################
