###################################################################################################

kind: Service
apiVersion: "{{ .Values.apiVersionService }}"
metadata:
  name: "{{ template "elasticsearchIngestName" . }}"
  namespace: "{{ template "elasticsearchNamespace" . }}"
  labels:
    name: "{{ template "elasticsearchIngestName" . }}"
    chart: "{{ template "elasticsearchChart" . }}"
    release: "{{ template "elasticsearchRelease" . }}"
    heritage: "{{ template "elasticsearchHeritage" . }}"
  {{- if or .Values.ingestServiceAnnotations (and (eq .Values.ingestServiceType "LoadBalancer") (or .Values.ingestServiceAwsInternalLoadBalancer .Values.ingestServiceGcpInternalLoadBalancer)) }}
  annotations:
    {{- if .Values.ingestServiceAwsInternalLoadBalancer }}
    service.beta.kubernetes.io/aws-load-balancer-internal: "true"
    {{- end }}
    {{- if .Values.ingestServiceGcpInternalLoadBalancer }}
    cloud.google.com/load-balancer-type: Internal
    {{- end }}
    {{- if .Values.ingestServiceAnnotations }}
{{ toYaml .Values.ingestServiceAnnotations | indent 4 }}
    {{- end }}
  {{- end }}
spec:
  type: "{{ .Values.ingestServiceType }}"
  selector:
    name: "{{ template "elasticsearchIngestName" . }}"
  ports:
    - name: "{{ .Values.httpWord }}"
      port: {{ .Values.httpPort }}
      targetPort: "{{ .Values.httpWord }}"

###################################################################################################
