###################################################################################################

kind: ConfigMap
apiVersion: "{{ .Values.apiVersionConfigMap }}"
metadata:
  name: "{{ template "elasticsearchIngestName" . }}"
  namespace: "{{ template "elasticsearchNamespace" . }}"
  labels:
    name: "{{ template "elasticsearchIngestName" . }}"
    chart: "{{ template "elasticsearchChart" . }}"
    release: "{{ template "elasticsearchRelease" . }}"
    heritage: "{{ template "elasticsearchHeritage" . }}"
data:
  {{ .Values.jvmFile }}: |
    -Xms{{ required ".Values.ingestJvmHeapSize" .Values.ingestJvmHeapSize }}
    -Xmx{{ required ".Values.ingestJvmHeapSize" .Values.ingestJvmHeapSize }}
    -Xss{{ .Values.jvmThreadStackSize }}
    -Xloggc:{{ template "elasticsearchIngestLogsBase" . }}/{{ .Values.jvmGcLogFile }}
    -Djna.nosys=true
    -Dfile.encoding={{ .Values.jvmFileEncoding }}
    -Djava.io.tmpdir=${ES_TMPDIR}
    -XX:GCLogFileSize={{ .Values.jvmGcLogFileSize }}
    -XX:+AlwaysPreTouch
    -Dio.netty.noUnsafe=true
    -Djava.awt.headless=true
    -XX:+PrintGCDetails
    -Dlog4j2.disable.jmx=true
    -XX:NumberOfGCLogFiles={{ .Values.jvmGcLogFiles }}
    -XX:+PrintGCDateStamps
    -XX:+UseConcMarkSweepGC
    -XX:+UseGCLogFileRotation
    {{- if (.Values.configNetworkHost | contains "ipv4") }}
    -Djava.net.preferIPv4Stack=true
    {{- end }}
    -Dlog4j.shutdownHookEnabled=false
    -XX:-OmitStackTraceInFastThrow
    -XX:+PrintTenuringDistribution
    -Dio.netty.noKeySetOptimization=true
    -XX:+PrintGCApplicationStoppedTime
    -XX:+UseCMSInitiatingOccupancyOnly
    -XX:CMSInitiatingOccupancyFraction={{ .Values.jmvCmsInitiatingOccupancyFraction }}
    -Dio.netty.recycler.maxCapacityPerThread=0

  {{ .Values.log4jFile }}: |
    status = {{ .Values.log4jStatus }}
    rootLogger.level = {{ .Values.log4jRootLevel }}
    appender.CONSOLE.name = CONSOLE
    appender.CONSOLE.type = Console
    appender.CONSOLE.layout.type = PatternLayout
    appender.CONSOLE.layout.pattern = {{ .Values.log4jAppenderLayoutPattern }}
    rootLogger.appenderRef.CONSOLE.ref = CONSOLE
    appender.ROLLINGRANDOMACCESSFILE.name = ROLLINGRANDOMACCESSFILE
    appender.ROLLINGRANDOMACCESSFILE.type = RollingRandomAccessFile
    appender.ROLLINGRANDOMACCESSFILE.fileName = {{ template "elasticsearchIngestLogsBase" . }}/{{ .Values.log4jRollingRandomAccessFileName }}
    appender.ROLLINGRANDOMACCESSFILE.fileGroup = {{ .Values.fsGroup }}
    appender.ROLLINGRANDOMACCESSFILE.fileOwner = {{ .Values.runAsUser }}
    {{- if .Values.log4jRollingRandomAccessFileBufferSize }}
    appender.ROLLINGRANDOMACCESSFILE.bufferSize = {{ .Values.log4jRollingRandomAccessFileBufferSize }}
    {{- end }}
    appender.ROLLINGRANDOMACCESSFILE.filePattern = {{ .Values.log4jRollingRandomAccessFilePattern }}
    appender.ROLLINGRANDOMACCESSFILE.layout.type = PatternLayout
    appender.ROLLINGRANDOMACCESSFILE.policy.size = {{ .Values.log4jRollingRandomAccessFileSize }}
    appender.ROLLINGRANDOMACCESSFILE.policy.type = SizeBasedTriggeringPolicy
    appender.ROLLINGRANDOMACCESSFILE.strategy.max = {{ .Values.log4jRollingRandomAccessFiles }}
    appender.ROLLINGRANDOMACCESSFILE.strategy.type = DefaultRolloverStrategy
    {{- if .Values.log4jRollingRandomAccessFileImmediateFlush }}
    appender.ROLLINGRANDOMACCESSFILE.immediateFlush = {{ .Values.log4jRollingRandomAccessFileImmediateFlush }}
    {{- end }}
    appender.ROLLINGRANDOMACCESSFILE.layout.pattern = {{ .Values.log4jAppenderLayoutPattern }}
    {{- if .Values.log4jRollingRandomAccessFilePermissions }}
    appender.ROLLINGRANDOMACCESSFILE.filePermissions = {{ .Values.log4jRollingRandomAccessFilePermissions }}
    {{- end }}
    rootLogger.appenderRef.ROLLINGRANDOMACCESSFILE.ref = ROLLINGRANDOMACCESSFILE

  {{ .Values.configFile }}: |
    http.port: {{ .Values.httpPort }}
    node.data: {{ .Values.ingestConfigNodeData }}
    path.data: {{ template "elasticsearchIngestDataBase" . }}
    path.logs: {{ template "elasticsearchIngestLogsBase" . }}
    processors: {{ .Values.ingestConfigProcessors }}
    node.ingest: {{ .Values.ingestConfigNodeIngest }}
    node.master: {{ .Values.ingestConfigNodeMaster }}
    cluster.name: {{ template "elasticsearchName" . }}
    network.host: {{ .Values.configNetworkHost }}
    transport.tcp.port: {{ .Values.clusterPort }}
    {{- if .Values.configNetworkTcpNoDelay }}
    network.tcp.no_delay: {{ .Values.configNetworkTcpNoDelay }}
    {{- end }}
    {{- if .Values.configNetworkTcpKeepAlive }}
    network.tcp.keep_alive: {{ .Values.configNetworkTcpKeepAlive }}
    {{- end }}
    {{- if .Values.configTransportTcpCompress }}
    transport.tcp.compress: {{ .Values.configTransportTcpCompress }}
    {{- end }}
    {{- if .Values.configTransportPingSchedule }}
    transport.ping_schedule: {{ .Values.configTransportPingSchedule }}
    {{- end }}
    {{- if .Values.configTransportTcpConnectTimeout }}
    transport.tcp.connect_timeout: {{ .Values.configTransportTcpConnectTimeout }}
    {{- end }}
    discovery.zen.ping.unicast.hosts: {{ template "elasticsearchClusterName" . }}
    discovery.zen.minimum_master_nodes: {{ template "elasticsearchMinimumMasterNodes" . }}

###################################################################################################
