###################################################################################################

kind: ConfigMap
apiVersion: "{{ .Values.apiVersionConfigMap }}"
metadata:
  name: "{{ template "elasticsearchIngestName" . }}"
  namespace: "{{ template "elasticsearchNamespace" . }}"
  labels:
    name: "{{ template "elasticsearchIngestName" . }}"
    chart: "{{ template "elasticsearchChart" . }}"
    release: "{{ template "elasticsearchRelease" . }}"
    heritage: "{{ template "elasticsearchHeritage" . }}"
data:
  {{ .Values.jvmFile }}: |
    -Xms{{ required ".Values.ingestJvmHeapSize" .Values.ingestJvmHeapSize }}
    -Xmx{{ required ".Values.ingestJvmHeapSize" .Values.ingestJvmHeapSize }}
    -Xss{{ .Values.ingestJvmThreadStackSize }}
    -Xloggc:{{ template "elasticsearchLogsBase" . }}/{{ .Values.jvmGcLogFile }}
    -Djna.nosys=true
    -Dfile.encoding=UTF-8
    -Djava.io.tmpdir=${ES_TMPDIR}
    -XX:GCLogFileSize={{ .Values.ingestJvmGcLogFileSize }}
    -XX:+AlwaysPreTouch
    -Dio.netty.noUnsafe=true
    -Djava.awt.headless=true
    -XX:+PrintGCDetails
    -Dlog4j2.disable.jmx=true
    -XX:NumberOfGCLogFiles={{ .Values.ingestJvmGcLogFiles }}
    -XX:+PrintGCDateStamps
    -XX:+UseConcMarkSweepGC
    -XX:+UseGCLogFileRotation
    {{- if (.Values.ingestConfigNetworkHost | contains "ipv4") }}
    -Djava.net.preferIPv4Stack=true
    {{- end }}
    -Dlog4j.shutdownHookEnabled=false
    -XX:-OmitStackTraceInFastThrow
    -XX:+PrintTenuringDistribution
    -Dio.netty.noKeySetOptimization=true
    -XX:+PrintGCApplicationStoppedTime
    -XX:+UseCMSInitiatingOccupancyOnly
    -XX:CMSInitiatingOccupancyFraction=75
    -Dio.netty.recycler.maxCapacityPerThread=0

  {{ .Values.log4jFile }}: |
    status = {{ .Values.ingestLog4jStatus }}
    rootLogger.level = {{ .Values.ingestLog4jRootLevel }}
    appender.CONSOLE.name = CONSOLE
    appender.CONSOLE.type = Console
    appender.CONSOLE.layout.type = PatternLayout
    appender.CONSOLE.layout.pattern = {{ .Values.log4jAppenderLayoutPattern }}
    rootLogger.appenderRef.CONSOLE.ref = CONSOLE
    appender.ROLLINGRANDOMACCESSFILE.name = ROLLINGRANDOMACCESSFILE
    appender.ROLLINGRANDOMACCESSFILE.type = RollingRandomAccessFile
    appender.ROLLINGRANDOMACCESSFILE.fileName = {{ template "elasticsearchLogsBase" . }}/{{ .Values.log4jFileName }}
    appender.ROLLINGRANDOMACCESSFILE.fileGroup = {{ .Values.fsGroup }}
    appender.ROLLINGRANDOMACCESSFILE.fileOwner = {{ .Values.runAsUser }}
    appender.ROLLINGRANDOMACCESSFILE.filePattern = {{ .Values.log4jFilePattern }}
    appender.ROLLINGRANDOMACCESSFILE.layout.type = PatternLayout
    appender.ROLLINGRANDOMACCESSFILE.policy.size = {{ .Values.ingestLog4jFileSize }}
    appender.ROLLINGRANDOMACCESSFILE.policy.type = SizeBasedTriggeringPolicy
    appender.ROLLINGRANDOMACCESSFILE.strategy.max = {{ .Values.ingestLog4jFiles }}
    appender.ROLLINGRANDOMACCESSFILE.strategy.type = DefaultRolloverStrategy
    appender.ROLLINGRANDOMACCESSFILE.immediateFlush = {{ .Values.ingestLog4jImmediateFlush }}
    appender.ROLLINGRANDOMACCESSFILE.layout.pattern = {{ .Values.log4jAppenderLayoutPattern }}
    rootLogger.appenderRef.ROLLINGRANDOMACCESSFILE.ref = ROLLINGRANDOMACCESSFILE

  {{ .Values.configFile }}: |
    http.port: {{ .Values.httpPort }}
    node.data: {{ .Values.ingestConfigNodeData }}
    path.data: {{ template "elasticsearchDataBase" . }}
    path.logs: {{ template "elasticsearchLogsBase" . }}
    processors: {{ .Values.ingestConfigProcessors }}
    node.ingest: {{ .Values.ingestConfigNodeIngest }}
    node.master: {{ .Values.ingestConfigNodeMaster }}
    cluster.name: {{ template "elasticsearchName" . }}
    network.host: {{ .Values.ingestConfigNetworkHost }}
    transport.tcp.port: {{ .Values.clusterPort }}
    discovery.zen.ping.unicast.hosts: {{ template "elasticsearchClusterName" . }}
    discovery.zen.minimum_master_nodes: {{ template "elasticsearchMinimumMasterNodes" . }}

###################################################################################################
