###################################################################################################

kind: ConfigMap
apiVersion: "{{ .Values.apiVersionConfigMap }}"
metadata:
  name: "{{ template "elasticsearchMasterName" . }}"
  namespace: "{{ template "elasticsearchNamespace" . }}"
  labels:
    name: "{{ template "elasticsearchMasterName" . }}"
    chart: "{{ template "elasticsearchChart" . }}"
    release: "{{ template "elasticsearchRelease" . }}"
    heritage: "{{ template "elasticsearchHeritage" . }}"
data:
  {{ .Values.clusterJvmFile }}: |
    -Xms{{ required ".Values.masterJvmHeapSize" .Values.masterJvmHeapSize }}
    -Xmx{{ required ".Values.masterJvmHeapSize" .Values.masterJvmHeapSize }}
    -Xss{{ .Values.masterJvmThreadStackSize }}
    -Xloggc:{{ template "elasticsearchMasterLogsBase" . }}/{{ .Values.clusterJvmGcLogFile }}
    -Djna.nosys=true
    -Dfile.encoding=UTF-8
    -Djava.io.tmpdir=${ES_TMPDIR}
    -XX:GCLogFileSize={{ .Values.masterJvmGcLogFileSize }}
    -XX:+AlwaysPreTouch
    -Dio.netty.noUnsafe=true
    -Djava.awt.headless=true
    -XX:+PrintGCDetails
    -Dlog4j2.disable.jmx=true
    -XX:NumberOfGCLogFiles={{ .Values.masterJvmGcLogFiles }}
    -XX:+PrintGCDateStamps
    -XX:+UseConcMarkSweepGC
    -XX:+UseGCLogFileRotation
    {{- if (.Values.masterConfigNetworkHost | contains "ipv4") }}
    -Djava.net.preferIPv4Stack=true
    {{- end }}
    -Dlog4j.shutdownHookEnabled=false
    -XX:-OmitStackTraceInFastThrow
    -XX:+PrintTenuringDistribution
    -Dio.netty.noKeySetOptimization=true
    -XX:+PrintGCApplicationStoppedTime
    -XX:+UseCMSInitiatingOccupancyOnly
    -XX:CMSInitiatingOccupancyFraction=75
    -Dio.netty.recycler.maxCapacityPerThread=0

  {{ .Values.clusterLog4jFile }}: |
    status = {{ .Values.masterLog4jStatus }}
    rootLogger.level = {{ .Values.masterLog4jRootLevel }}
    appender.CONSOLE.name = CONSOLE
    appender.CONSOLE.type = Console
    appender.CONSOLE.layout.type = PatternLayout
    appender.CONSOLE.layout.pattern = {{ .Values.clusterLog4jAppenderLayoutPattern }}
    rootLogger.appenderRef.CONSOLE.ref = CONSOLE
    appender.ROLLINGRANDOMACCESSFILE.name = ROLLINGRANDOMACCESSFILE
    appender.ROLLINGRANDOMACCESSFILE.type = RollingRandomAccessFile
    appender.ROLLINGRANDOMACCESSFILE.fileName = {{ template "elasticsearchMasterLogsBase" . }}/{{ .Values.clusterLog4jFileName }}
    appender.ROLLINGRANDOMACCESSFILE.fileGroup = {{ .Values.clusterFsGroup }}
    appender.ROLLINGRANDOMACCESSFILE.fileOwner = {{ .Values.clusterRunAsUser }}
    appender.ROLLINGRANDOMACCESSFILE.filePattern = {{ .Values.clusterLog4jFilePattern }}
    appender.ROLLINGRANDOMACCESSFILE.layout.type = PatternLayout
    appender.ROLLINGRANDOMACCESSFILE.policy.size = {{ .Values.masterLog4jFileSize }}
    appender.ROLLINGRANDOMACCESSFILE.policy.type = SizeBasedTriggeringPolicy
    appender.ROLLINGRANDOMACCESSFILE.strategy.max = {{ .Values.masterLog4jFiles }}
    appender.ROLLINGRANDOMACCESSFILE.strategy.type = DefaultRolloverStrategy
    appender.ROLLINGRANDOMACCESSFILE.immediateFlush = {{ .Values.masterLog4jImmediateFlush }}
    appender.ROLLINGRANDOMACCESSFILE.layout.pattern = {{ .Values.clusterLog4jAppenderLayoutPattern }}
    rootLogger.appenderRef.ROLLINGRANDOMACCESSFILE.ref = ROLLINGRANDOMACCESSFILE

  {{ .Values.clusterConfigFile }}: |
    http.port: {{ .Values.clusterHttpPort }}
    node.data: {{ .Values.masterConfigNodeData }}
    path.data: {{ template "elasticsearchMasterDataBase" . }}
    path.logs: {{ template "elasticsearchMasterLogsBase" . }}
    processors: {{ .Values.masterConfigProcessors }}
    node.ingest: {{ .Values.masterConfigNodeIngest }}
    node.master: {{ .Values.masterConfigNodeMaster }}
    cluster.name: {{ template "elasticsearchName" . }}
    network.host: {{ .Values.masterConfigNetworkHost }}
    transport.tcp.port: {{ .Values.clusterTransportPort }}
    discovery.zen.ping.unicast.hosts: {{ template "elasticsearchClusterName" . }}
    discovery.zen.minimum_master_nodes: {{ template "elasticsearchClusterMinimumMasterNodes" . }}

###################################################################################################
