###################################################################################################

kind: PodDisruptionBudget
apiVersion: "{{ .Values.apiVersionPodDisruptionBudget }}"
metadata:
  name: "{{ template "elasticsearchMasterName" . }}"
  namespace: "{{ template "elasticsearchNamespace" . }}"
  labels:
    name: "{{ template "elasticsearchMasterName" . }}"
    chart: "{{ template "elasticsearchChart" . }}"
    release: "{{ template "elasticsearchRelease" . }}"
    heritage: "{{ template "elasticsearchHeritage" . }}"
spec:
  selector:
    matchLabels:
      name: "{{ template "elasticsearchMasterName" . }}"
  {{- if .Values.masterPodMinAvailable }}
  minAvailable: {{ .Values.masterPodMinAvailable }}
  {{- else }}
  maxUnavailable: {{ .Values.masterPodMaxUnavailable }}
  {{- end }}

###################################################################################################
