###################################################################################################

kind: StatefulSet
apiVersion: "{{ .Values.apiVersionStatefulSet }}"
metadata:
  name: "{{ template "elasticsearchName" . }}"
  namespace: "{{ template "elasticsearchNamespace" . }}"
  labels:
    name: "{{ template "elasticsearchName" . }}"
    chart: "{{ template "elasticsearchChart" . }}"
    release: "{{ template "elasticsearchRelease" . }}"
    heritage: "{{ template "elasticsearchHeritage" . }}"
  annotations:
    config.sha256sum: "{{ include (print .Template.BasePath "/config-map.yaml") . | sha256sum }}"
spec:
  selector:
    matchLabels:
      name: "{{ template "elasticsearchName" . }}"
  replicas: {{ .Values.replicas }}
  serviceName: "{{ template "elasticsearchName" . }}"
  {{- if or .Values.volumeDataEnabled .Values.volumeLogsEnabled }}
  volumeClaimTemplates:
    {{- if .Values.volumeDataEnabled }}
    - metadata:
        name: "{{ .Values.volumeDataName }}"
        annotations:
          volume.alpha.kubernetes.io/storage-class: "{{ .Values.volumeDataClass }}"
      spec:
        resources:
          requests:
            storage: "{{ .Values.volumeDataSize }}"
        accessModes: [ "{{ .Values.volumeDataMode }}" ]
    {{- end }}
    {{- if .Values.volumeLogsEnabled }}
    - metadata:
        name: "{{ .Values.volumeLogsName }}"
        annotations:
          volume.alpha.kubernetes.io/storage-class: "{{ .Values.volumeLogsClass }}"
      spec:
        resources:
          requests:
            storage: "{{ .Values.volumeLogsSize }}"
        accessModes: [ "{{ .Values.volumeLogsMode }}" ]
    {{- end }}
  {{- end }}
  template:
    metadata:
      labels:
        name: "{{ template "elasticsearchName" . }}"
        chart: "{{ template "elasticsearchChart" . }}"
        release: "{{ template "elasticsearchRelease" . }}"
        heritage: "{{ template "elasticsearchHeritage" . }}"
        {{- if .Values.podLabels }}
{{ toYaml .Values.podLabels | indent 8 }}
        {{- end }}
      {{- if .Values.podAnnotations }}
      annotations:
{{ toYaml .Values.podAnnotations | indent 8 }}
      {{- end }}
    spec:
      affinity:
        podAntiAffinity:
          {{- if eq (.Values.podAntiAffinity | lower) "required" }}
          requiredDuringSchedulingIgnoredDuringExecution:
            - topologyKey: "{{ .Values.podAntiAffinityTopologyKey }}"
              labelSelector:
                matchExpressions:
                  - key: name
                    values: [ "{{ template "elasticsearchName" . }}" ]
                    operator: In
          {{- else }}
          preferredDuringSchedulingIgnoredDuringExecution:
            - weight: {{ .Values.podAntiAffinityWeight }}
              podAffinityTerm:
                topologyKey: "{{ .Values.podAntiAffinityTopologyKey }}"
                labelSelector:
                  matchExpressions:
                    - key: name
                      values: [ "{{ template "elasticsearchName" . }}" ]
                      operator: In
          {{- end }}
      {{- if or (ge (default 0 (.Values.fsGroup | int)) 0) (ge (default 0 (.Values.runAsUser | int)) 0) }}
      securityContext:
        {{- if ge (default 0 (.Values.fsGroup | int)) 0 }}
        fsGroup: {{ .Values.fsGroup }}
        {{- end }}
        {{- if ge (default 0 (.Values.runAsUser | int)) 0 }}
        runAsUser: {{ .Values.runAsUser }}
        {{- end }}
      {{- end }}
      {{- if .Values.podNodeSelector }}
      nodeSelector:
{{ toYaml .Values.podNodeSelector | indent 8 }}
      {{- end }}
      {{- if .Values.podTolerations }}
      tolerations:
{{ toYaml .Values.podTolerations | indent 8 }}
      {{- end }}
      volumes:
        - name: "{{ template "elasticsearchName" . }}"
          configMap:
            name: "{{ template "elasticsearchName" . }}"
        {{- if not .Values.volumeDataEnabled }}
        - name: "{{ .Values.volumeDataName }}"
          emptyDir: {}
        {{- end }}
        {{- if not .Values.volumeLogsEnabled }}
        - name: "{{ .Values.volumeLogsName }}"
          emptyDir: {}
        {{- end }}
      {{- if .Values.podVolumes }}
{{ toYaml .Values.podVolumes | indent 8 }}
      {{- end }}
      containers:
        - name: "{{ .Chart.Name }}"
          image: "{{ template "elasticsearchImage" . }}"
          imagePullPolicy: "{{ .Values.imagePullPolicy }}"
          securityContext:
            allowPrivilegeEscalation: {{ .Values.allowPrivilegeEscalation }}
          env:
            - name: node.name
              valueFrom:
                fieldRef:
                  fieldPath: metadata.name
            {{- if (.Values.configNetworkHost | contains "ipv4") }}
            - name: ES_JAVA_OPTS
              value: "-Djava.net.preferIPv4Stack=true"
            {{- end }}
          ports:
            - name: "{{ .Values.httpName }}"
              containerPort: {{ .Values.httpPort }}
            - name: "{{ .Values.transportName }}"
              containerPort: {{ .Values.transportPort }}
          {{- if or .Values.cpuMinimum .Values.cpuMaximum .Values.memoryMinimum .Values.memoryMaximum }}
          resources:
            {{- if or .Values.cpuMinimum .Values.memoryMinimum }}
            requests:
              {{- if .Values.cpuMinimum }}
              cpu: "{{ .Values.cpuMinimum }}"
              {{- end }}
              {{- if .Values.memoryMinimum }}
              memory: "{{ .Values.memoryMinimum }}"
              {{- end }}
            {{- end }}
            {{- if or .Values.cpuMaximum .Values.memoryMaximum }}
            limits:
              {{- if .Values.cpuMaximum }}
              cpu: "{{ .Values.cpuMaximum }}"
              {{- end }}
              {{- if .Values.memoryMaximum }}
              memory: "{{ .Values.memoryMaximum }}"
              {{- end }}
            {{- end }}
          {{- end }}
          volumeMounts:
            - name: "{{ template "elasticsearchName" . }}"
              subPath: "{{ .Values.configFile }}"
              mountPath: "{{ template "elasticsearchConfigMountBase" . }}/{{ .Values.configFile }}"
            - name: "{{ template "elasticsearchName" . }}"
              subPath: "{{ .Values.log4jFile }}"
              mountPath: "{{ template "elasticsearchConfigMountBase" . }}/{{ .Values.log4jFile }}"
            - name: "{{ .Values.volumeDataName }}"
              mountPath: "{{ template "elasticsearchVolumeDataMount" . }}"
            - name: "{{ .Values.volumeLogsName }}"
              mountPath: "{{ template "elasticsearchVolumeLogsMount" . }}"
          {{- if .Values.podVolumeMounts }}
{{ toYaml .Values.podVolumeMounts | indent 12 }}
          {{- end }}
          livenessProbe:
            tcpSocket:
              port: "{{ .Values.transportName }}"
            periodSeconds: {{ .Values.livenessProbePeriodSeconds }}
            timeoutSeconds: {{ .Values.livenessProbeTimeoutSeconds }}
            successThreshold: {{ .Values.livenessProbeSuccessThreshold }}
            failureThreshold: {{ .Values.livenessProbeFailureThreshold }}
            initialDelaySeconds: {{ .Values.livenessProbeInitialDelaySeconds }}
          readinessProbe:
            tcpSocket:
              port: "{{ .Values.transportName }}"
            periodSeconds: {{ .Values.readinessProbePeriodSeconds }}
            timeoutSeconds: {{ .Values.readinessProbeTimeoutSeconds }}
            successThreshold: {{ .Values.readinessProbeSuccessThreshold }}
            failureThreshold: {{ .Values.readinessProbeFailureThreshold }}

###################################################################################################
