###################################################################################################

kind: NetworkPolicy
apiVersion: "{{ .Values.apiVersionNetworkPolicy }}"
metadata:
  name: "{{ template "elasticsearchTransportName" . }}"
  namespace: "{{ template "elasticsearchNamespace" . }}"
  labels:
    name: "{{ template "elasticsearchTransportName" . }}"
    chart: "{{ template "elasticsearchChart" . }}"
    release: "{{ template "elasticsearchRelease" . }}"
    heritage: "{{ template "elasticsearchHeritage" . }}"
spec:
  podSelector:
    matchLabels:
      chart: "{{ template "elasticsearchChart" . }}"
      release: "{{ template "elasticsearchRelease" . }}"
      heritage: "{{ template "elasticsearchHeritage" . }}"
  ingress:
    - ports:
        - port: {{ .Values.transportPort }}
      from:
        - podSelector:
            matchLabels:
              chart: "{{ template "elasticsearchChart" . }}"
              release: "{{ template "elasticsearchRelease" . }}"
              heritage: "{{ template "elasticsearchHeritage" . }}"

###################################################################################################
