###################################################################################################

#replicas: 1
log4jRollingRandomAccessFileImmediateFlush: true

# https://github.com/clockworksoul/helm-elasticsearch
# https://github.com/pires/kubernetes-elasticsearch-cluster
# https://www.elastic.co/guide/en/elasticsearch/reference/current/modules-node.html

###################################################################################################
