###################################################################################################

replicas: 3

###################################################################################################

logLevel: trace

###################################################################################################

storage:
  dynamodb:
    table: Vault
    region: eu-west-1
    ha_enabled: 'true'

###################################################################################################

# Initialise
# ----------
#
# kubectl exec --namespace default vault-vault-0 -c vault -- vault operator init -address=http://127.0.0.1:8200
#
# Unseal
# ------
#
# kubectl exec --namespace default vault-vault-0 -c vault -- vault operator unseal -address=http://127.0.0.1:8200 <<KEY>>
# kubectl exec --namespace default vault-vault-1 -c vault -- vault operator unseal -address=http://127.0.0.1:8200 <<KEY>>
# kubectl exec --namespace default vault-vault-2 -c vault -- vault operator unseal -address=http://127.0.0.1:8200 <<KEY>>

###################################################################################################
